data_
#
loop_
_ptcls_polish.id
_ptcls_polish.label
_ptcls_polish.icon
_ptcls_polish.widget
_ptcls_polish.value
_ptcls_polish.help
io                   "I/O"                      bi-arrow-down-up    tab              ?        ?
settings             "Settings"                bi-tools             tab              ?        ?
log                  "Log"                     bi-binoculars-fill   tab              ?        ?
dataviz              "DataViz"                 bi-eye               tab              ?        ?
#
loop_
_io.id
_io.label
_io.icon
_io.widget
_io.value
_io.display
_io.help
indata               "Input Data"                             bi-box-arrow-in-down fieldset   ?          show       ?
outdata              "Output Data"                            bi-box-arrow-down    fieldset   ?          hidden     ?
nodes                "Nodes"                                  bi-controller        fieldset   ?          hidden     ?
system               "System"                                 bi-incognito         fieldset   ?          hiddden    ?
ptcls_polish_cmd     "Check command"                          bi-chat-right-text   cli        ?          show       ?
#
loop_
_indata.id
_indata.label
_indata.widget
_indata.default
_indata.arg0
_indata.arg1
_indata.arg2
_indata.constraint
_indata.help
fn_mic               "Micrographs (from MotionCorr):"    file       ?               "MicrographGroupMetadata.star.relion" 1               "STAR files (*.star)" required        
; The input STAR file with the micrograph (and their movie metadata) from a MotionCorr job.
;
fn_data              "Particles (from Refine3D or CtfRefine):" file       ?               "ParticleGroupMetadata.star.relion" 1               "STAR files (*.star)" required        "The input STAR file with the metadata of all particles."
fn_post              "Postprocess STAR file:"            file       ?               "ProcessData.star.relion.postprocess" 1               "STAR files (postprocess.star)" required        
; The STAR file generated by a PostProcess job.
The mask used for this postprocessing will be applied to the unfiltered half-maps and should encompass the entire complex.
The resulting FSC curve will be used for weighting the different frequencies.
;
#
loop_
_outdata.id
_outdata.label
_outdata.widget
_outdata.default
_outdata.arg0
_outdata.arg1
_outdata.arg2
_outdata.constraint
_outdata.help
#
loop_
_nodes.id
_nodes.label
_nodes.widget
_nodes.default
_nodes.arg0
_nodes.arg1
_nodes.arg2
_nodes.constraint
_nodes.help
#
loop_
_system.id
_system.label
_system.widget
_system.default
_system.arg0
_system.arg1
_system.arg2
_system.constraint
_system.help
do_polish            "Perform particle polishing?"       bool       true            "?"             "?"             "?"             ?               
; If set to Yes, then relion_motion_refine will be run to estimate per-particle motion-tracks using the parameters below, and polished particles will be generated.
;
#
loop_
_ptcls_polish_cmd.id
_ptcls_polish_cmd.label
_ptcls_polish_cmd.widget
_ptcls_polish_cmd.default
_ptcls_polish_cmd.arg0
_ptcls_polish_cmd.arg1
_ptcls_polish_cmd.arg2
_ptcls_polish_cmd.constraint
_ptcls_polish_cmd.help
#
loop_
_settings.id
_settings.label
_settings.icon
_settings.widget
_settings.value
_settings.display
_settings.help
general              "General"                                bi-chat-right-text   fieldset   ?          show       ?
params_01            "Parameters"                             bi-chat-right-text   fieldset   ?          show       ?
do_param_optim       "Train optimal parameters?"              bi-chat-right-text   switch     ?          show       ?
do_polish_fs         "Perform particle polishing"             bi-chat-right-text   fieldset   ?          show       ?
do_own_params        "OR use your own parameters?"            bi-chat-right-text   switch     ?          show       ?
parallel_computing   "Parallel Computing"                     bi-chat-right-text   fieldset   ?          show       ?
#
loop_
_general.id
_general.label
_general.widget
_general.default
_general.arg0
_general.arg1
_general.arg2
_general.constraint
_general.help
first_frame          "First movie frame: "               range      1.0             1.0             10.0            1               ?               
; First movie frame to take into account in motion fit and combination step
;
last_frame           "Last movie frame: "                range      -1.0            5.0             50.0            1               ?               
; Last movie frame to take into account in motion fit and combination step.
Values equal to or smaller than 0 mean 'use all frames'.
;
#
loop_
_params_01.id
_params_01.label
_params_01.widget
_params_01.default
_params_01.arg0
_params_01.arg1
_params_01.arg2
_params_01.constraint
_params_01.help
extract_size         "Extraction size (pix in unbinned movie):" range      -1              64              1024            8               ?               
; Size of the extracted particles in the unbinned original movie(in pixels).
This should be an even number.
;
rescale              "Re-scaled size (pixels): "         range      -1              64              1024            8               ?               "The re-scaled value needs to be an even number."
do_float16           "Write output in float16?"          bool       true            "?"             "?"             "?"             ?               
; If set to Yes, this program will write output images in float16 MRC format.
This will save a factor of two in disk space compared to the default of writing in float32.
Note that RELION and CCPEM will read float16 images, but other programs may not (yet) do so.
;
#
loop_
_do_param_optim.id
_do_param_optim.label
_do_param_optim.widget
_do_param_optim.default
_do_param_optim.arg0
_do_param_optim.arg1
_do_param_optim.arg2
_do_param_optim.constraint
_do_param_optim.help
eval_frac            "Fraction of Fourier pixels for testing: " range      0.5             0               1.0             0.01            ?               
; This fraction of Fourier pixels (at higher resolution) will be used for evaluation of the parameters (test set), whereas the rest (at lower resolution) will be used for parameter estimation itself (work set).
;
optim_min_part       "Use this many particles: "         range      10000           5000            50000           1000            ?               
; Use at least this many particles for the meta-parameter optimisation.
The more particles the more expensive in time and computer memory the calculation becomes, but the better the results may get.
;
#
loop_
_do_polish_fs.id
_do_polish_fs.label
_do_polish_fs.widget
_do_polish_fs.default
_do_polish_fs.arg0
_do_polish_fs.arg1
_do_polish_fs.arg2
_do_polish_fs.constraint
_do_polish_fs.help
opt_params           "Optimised parameter file:"         file       ?               "ParamsData.txt.relion.polish" 1               "TXT files (*.txt)" ?               
; The output TXT file from a previous Bayesian polishing job in which the optimal parameters were determined.
;
minres               "Minimum resolution for B-factor fit (A): " range      20              8               40              1               ?               
; The minimum spatial frequency (in Angstrom) used in the B-factor fit.
;
maxres               "Maximum resolution for B-factor fit (A): " range      -1              -1              15              1               ?               
; The maximum spatial frequency (in Angstrom) used in the B-factor fit.
If a negative value is given, the maximum is determined from the input FSC curve.
;
#
loop_
_do_own_params.id
_do_own_params.label
_do_own_params.widget
_do_own_params.default
_do_own_params.arg0
_do_own_params.arg1
_do_own_params.arg2
_do_own_params.constraint
_do_own_params.help
sigma_vel            "Sigma for velocity (A/dose): "     range      0.2             1.0             10.0            0.1             ?               
; Standard deviation for the velocity regularisation.
Smaller values requires the tracks to be shorter.
;
sigma_div            "Sigma for divergence (A): "        range      5000            0               10000           10000           ?               
; Standard deviation for the divergence of tracks across the micrograph.
Smaller values requires the tracks to be spatially more uniform in a micrograph.
;
sigma_acc            "Sigma for acceleration (A/dose): " range      2               -1              7               0.1             ?               
; Standard deviation for the acceleration regularisation.
Smaller values requires the tracks to be straighter.
;
#
loop_
_parallel_computing.id
_parallel_computing.label
_parallel_computing.widget
_parallel_computing.default
_parallel_computing.arg0
_parallel_computing.arg1
_parallel_computing.arg2
_parallel_computing.constraint
_parallel_computing.help
nr_mpi               "Number of MPI procs:"              range      {QSUB_NRMPI_VAL} 1               "{RELION_MPI_MAX}" 1               ?               
; Number of MPI nodes to use in parallel.
When set to 1, MPI will not be used.
The maximum can be set through the environment variable RELION_MPI_MAX.
;
nr_threads           "Number of threads:"                range      {QSUB_NRTHREADS_VAL} 1               "{RELION_THREAD_MAX}" 1               ?               
; Number of shared-memory (POSIX) threads to use in parallel.
When set to 1, no multi-threading will be used.
The maximum can be set through the environment variable RELION_THREAD_MAX.
;
#
loop_
_log.id
_log.label
_log.icon
_log.widget
_log.value
_log.display
_log.help
#
loop_
_dataviz.id
_dataviz.label
_dataviz.icon
_dataviz.widget
_dataviz.value
_dataviz.display
_dataviz.help
#
