data_
#
loop_
_anisomag.id
_anisomag.label
_anisomag.icon
_anisomag.widget
_anisomag.value
_anisomag.help
io                   "I/O"                      bi-arrow-down-up    tab              ?        ?
settings             "Settings"                bi-tools             tab              ?        ?
log                  "Log"                     bi-binoculars-fill   tab              ?        ?
dataviz              "DataViz"                 bi-eye               tab              ?        ?
#
loop_
_io.id
_io.label
_io.icon
_io.widget
_io.value
_io.display
_io.help
indata               "Input Data"                             bi-box-arrow-in-down fieldset   ?          show       ?
outdata              "Output Data"                            bi-box-arrow-down    fieldset   ?          hidden     ?
nodes                "Nodes"                                  bi-controller        fieldset   ?          hidden     ?
system               "System"                                 bi-incognito         fieldset   ?          hiddden    ?
anisomag_cmd         "Check command"                          bi-chat-right-text   cli        ?          show       ?
#
loop_
_indata.id
_indata.label
_indata.widget
_indata.default
_indata.arg0
_indata.arg1
_indata.arg2
_indata.constraint
_indata.help
fn_data              "Particles (from Refine3D):"        file       ?               "ParticleGroupMetadata.star.relion" 1               "STAR files (*.star)" required        "The input STAR file with the metadata of all particles."
fn_post              "Postprocess STAR file:"            file       ?               "ProcessData.star.relion.postprocess" 1               "STAR files (postprocess.star)" required        
; The STAR file generated by a PostProcess job.
The mask used for this postprocessing will be applied to the unfiltered half-maps and should encompass the entire complex.
The resulting FSC curve will be used for weighting the different frequencies.

 
 Note that for helices it is common practice to use a mask only encompassing the central 30% or so of the box.
This gives higher resolution estimates, as it disregards ill-defined regions near the box edges.
However, for ctf_refine it is better to use a mask encompassing (almost) the entire box, as otherwise there may not be enough signal.
;
#
loop_
_outdata.id
_outdata.label
_outdata.widget
_outdata.default
_outdata.arg0
_outdata.arg1
_outdata.arg2
_outdata.constraint
_outdata.help
#
loop_
_nodes.id
_nodes.label
_nodes.widget
_nodes.default
_nodes.arg0
_nodes.arg1
_nodes.arg2
_nodes.constraint
_nodes.help
#
loop_
_system.id
_system.label
_system.widget
_system.default
_system.arg0
_system.arg1
_system.arg2
_system.constraint
_system.help
do_aniso_mag         "Estimate (anisotropic) magnification?" bool       true            "?"             "?"             "?"             ?               
; If set to Yes, then relion_ctf_refine will also estimate the (anisotropic) magnification per optics group.
This option cannot be done simultaneously with higher-order aberration estimation.
It's probably best to estimate the one that is most off first, and the other one second.
It might be worth repeating the estimation if both are off.
;
#
loop_
_anisomag_cmd.id
_anisomag_cmd.label
_anisomag_cmd.widget
_anisomag_cmd.default
_anisomag_cmd.arg0
_anisomag_cmd.arg1
_anisomag_cmd.arg2
_anisomag_cmd.constraint
_anisomag_cmd.help
#
loop_
_settings.id
_settings.label
_settings.icon
_settings.widget
_settings.value
_settings.display
_settings.help
do_aniso_mag_fs      "Anisotropic Magnification Estimation Parameters" bi-chat-right-text   fieldset   ?          show       ?
do_ctf               "Perform CTF parameter fitting?"         bi-chat-right-text   switch     ?          show       ?
do_defocus           "Options"                                bi-chat-right-text   fieldset   ?          show       ?
do_astig             "Options"                                bi-chat-right-text   fieldset   ?          show       ?
do_bfactor           "Options"                                bi-chat-right-text   fieldset   ?          show       ?
do_phase             "Options"                                bi-chat-right-text   fieldset   ?          show       ?
do_tilt              "Estimate beamtilt?"                     bi-chat-right-text   switch     ?          show       ?
general              "General"                                bi-chat-right-text   fieldset   ?          show       ?
parallel_computing   "Parallel Computing"                     bi-chat-right-text   fieldset   ?          show       ?
#
loop_
_do_aniso_mag_fs.id
_do_aniso_mag_fs.label
_do_aniso_mag_fs.widget
_do_aniso_mag_fs.default
_do_aniso_mag_fs.arg0
_do_aniso_mag_fs.arg1
_do_aniso_mag_fs.arg2
_do_aniso_mag_fs.constraint
_do_aniso_mag_fs.help
do_4thorder          "Estimate 4th order aberrations?"   bool       false           "?"             "?"             "?"             ?               
; If set to Yes, then relion_ctf_refine will also estimate the Cs and the tetrafoil (4-fold astigmatism) per optics group.
This option is only recommended for data sets that extend beyond 3 Angstrom resolution.
;
#
loop_
_do_ctf.id
_do_ctf.label
_do_ctf.widget
_do_ctf.default
_do_ctf.arg0
_do_ctf.arg1
_do_ctf.arg2
_do_ctf.constraint
_do_ctf.help
do_defocus           "Fit defocus?"                      select     0               0               "?"             "?"             ?               
; If set to per-particle or per-micrograph, then relion_ctf_refine will estimate defocus values.
;
do_astig             "Fit astigmatism?"                  select     0               0               "?"             "?"             ?               
; If set to per-particle or per-micrograph, then relion_ctf_refine will estimate astigmatism.
;
do_bfactor           "Fit B-factor?"                     select     0               0               "?"             "?"             ?               
; If set to per-particle or per-micrograph, then relion_ctf_refine will estimate B-factors that describe the signal falloff.
;
do_phase             "Fit phase-shift?"                  select     0               0               "?"             "?"             ?               
; If set to per-particle or per-micrograph, then relion_ctf_refine will estimate (VPP?) phase shift values.
;
#
loop_
_do_defocus.id
_do_defocus.label
_do_defocus.widget
_do_defocus.default
_do_defocus.arg0
_do_defocus.arg1
_do_defocus.arg2
_do_defocus.constraint
_do_defocus.help
do_defocus_opt_00    "No"                                option     0               "?"             "?"             "?"             ?               "?"
do_defocus_opt_01    "Per-micrograph"                    option     1               "?"             "?"             "?"             ?               "?"
do_defocus_opt_02    "Per-particle"                      option     2               "?"             "?"             "?"             ?               "?"
#
loop_
_do_astig.id
_do_astig.label
_do_astig.widget
_do_astig.default
_do_astig.arg0
_do_astig.arg1
_do_astig.arg2
_do_astig.constraint
_do_astig.help
do_astig_opt_00      "No"                                option     0               "?"             "?"             "?"             ?               "?"
do_astig_opt_01      "Per-micrograph"                    option     1               "?"             "?"             "?"             ?               "?"
do_astig_opt_02      "Per-particle"                      option     2               "?"             "?"             "?"             ?               "?"
#
loop_
_do_bfactor.id
_do_bfactor.label
_do_bfactor.widget
_do_bfactor.default
_do_bfactor.arg0
_do_bfactor.arg1
_do_bfactor.arg2
_do_bfactor.constraint
_do_bfactor.help
do_bfactor_opt_00    "No"                                option     0               "?"             "?"             "?"             ?               "?"
do_bfactor_opt_01    "Per-micrograph"                    option     1               "?"             "?"             "?"             ?               "?"
do_bfactor_opt_02    "Per-particle"                      option     2               "?"             "?"             "?"             ?               "?"
#
loop_
_do_phase.id
_do_phase.label
_do_phase.widget
_do_phase.default
_do_phase.arg0
_do_phase.arg1
_do_phase.arg2
_do_phase.constraint
_do_phase.help
do_phase_opt_00      "No"                                option     0               "?"             "?"             "?"             ?               "?"
do_phase_opt_01      "Per-micrograph"                    option     1               "?"             "?"             "?"             ?               "?"
do_phase_opt_02      "Per-particle"                      option     2               "?"             "?"             "?"             ?               "?"
#
loop_
_do_tilt.id
_do_tilt.label
_do_tilt.widget
_do_tilt.default
_do_tilt.arg0
_do_tilt.arg1
_do_tilt.arg2
_do_tilt.constraint
_do_tilt.help
do_trefoil           "Also estimate trefoil?"            bool       false           "?"             "?"             "?"             ?               
; If set to Yes, then relion_ctf_refine will also estimate the trefoil (3-fold astigmatism) per optics group.
This option is only recommended for data sets that extend beyond 3.5 Angstrom resolution.
;
#
loop_
_general.id
_general.label
_general.widget
_general.default
_general.arg0
_general.arg1
_general.arg2
_general.constraint
_general.help
minres               "Minimum resolution for fits (A): " range      30              8               40              1               ?               
; The minimum spatial frequency (in Angstrom) used in the beamtilt fit.
;
#
loop_
_parallel_computing.id
_parallel_computing.label
_parallel_computing.widget
_parallel_computing.default
_parallel_computing.arg0
_parallel_computing.arg1
_parallel_computing.arg2
_parallel_computing.constraint
_parallel_computing.help
nr_mpi               "Number of MPI procs:"              range      {QSUB_NRMPI_VAL} 1               "{RELION_MPI_MAX}" 1               ?               
; Number of MPI nodes to use in parallel.
When set to 1, MPI will not be used.
The maximum can be set through the environment variable RELION_MPI_MAX.
;
nr_threads           "Number of threads:"                range      {QSUB_NRTHREADS_VAL} 1               "{RELION_THREAD_MAX}" 1               ?               
; Number of shared-memory (POSIX) threads to use in parallel.
When set to 1, no multi-threading will be used.
The maximum can be set through the environment variable RELION_THREAD_MAX.
;
#
loop_
_log.id
_log.label
_log.icon
_log.widget
_log.value
_log.display
_log.help
#
loop_
_dataviz.id
_dataviz.label
_dataviz.icon
_dataviz.widget
_dataviz.value
_dataviz.display
_dataviz.help
#
