data_
#
loop_
_log_filter.id
_log_filter.label
_log_filter.icon
_log_filter.widget
_log_filter.value
_log_filter.help
io                   "I/O"                      bi-arrow-down-up    tab              ?        ?
settings             "Settings"                bi-tools             tab              ?        ?
log                  "Log"                     bi-binoculars-fill   tab              ?        ?
dataviz              "DataViz"                 bi-eye               tab              ?        ?
#
loop_
_io.id
_io.label
_io.icon
_io.widget
_io.value
_io.display
_io.help
indata               "Input Data"                             bi-box-arrow-in-down fieldset   ?          show       ?
outdata              "Output Data"                            bi-box-arrow-down    fieldset   ?          hidden     ?
nodes                "Nodes"                                  bi-controller        fieldset   ?          hidden     ?
system               "System"                                 bi-incognito         fieldset   ?          hiddden    ?
log_filter_cmd       "Check command"                          bi-chat-right-text   cli        ?          show       ?
#
loop_
_indata.id
_indata.label
_indata.widget
_indata.default
_indata.arg0
_indata.arg1
_indata.arg2
_indata.constraint
_indata.help
fn_input_autopick    "Input micrographs for autopick:"   file       ?               "MicrographGroupMetadata.star.relion" 1               "Input micrographs (*.{star})" required        
; Input STAR file (preferably with CTF information) with all micrographs to pick from.
;
angpix               "Pixel size in micrographs (A)"     range      -1              0.3             5               0.1             ?               
; Pixel size in Angstroms.
If a CTF-containing STAR file is input, then the value given here will be ignored, and the pixel size will be calculated from the values in the STAR file.
A negative value can then be given here.
;
#
loop_
_outdata.id
_outdata.label
_outdata.widget
_outdata.default
_outdata.arg0
_outdata.arg1
_outdata.arg2
_outdata.constraint
_outdata.help
#
loop_
_nodes.id
_nodes.label
_nodes.widget
_nodes.default
_nodes.arg0
_nodes.arg1
_nodes.arg2
_nodes.constraint
_nodes.help
#
loop_
_system.id
_system.label
_system.widget
_system.default
_system.arg0
_system.arg1
_system.arg2
_system.constraint
_system.help
do_log               "OR: use Laplacian-of-Gaussian?"    bool       true            "?"             "?"             "?"             ?               
; If set to Yes, a Laplacian-of-Gaussian blob detection will be used (you can then leave the 'References' field empty.
The preferred way to autopick is by setting this to no and providing references that were generated by 2D classification from this data set in RELION.
The Laplacian-of-Gaussian method may be useful to kickstart a new data set.
Please note that some options in the autopick tab are ignored in this method.
See help messages of each option for details.
;
do_refs              "Use reference-based template-matching?" bool       false           "?"             "?"             "?"             ?               
; If set to Yes, 2D or 3D references, as defined on the References tab will be used for autopicking.
;
do_ref3d             "OR: provide a 3D reference?"       bool       false           "?"             "?"             "?"             ?               
; Set this option to Yes if you want to provide a 3D map, which will be projected into multiple directions to generate 2D references.
;
do_topaz_train       "Perform topaz training?"           bool       false           "?"             "?"             "?"             ?               "Set this option to Yes if you want to train a topaz model."
do_topaz_pick        "Perform topaz picking?"            bool       false           "?"             "?"             "?"             ?               
; Set this option to Yes if you want to use a topaz model for autopicking.
;
#
loop_
_log_filter_cmd.id
_log_filter_cmd.label
_log_filter_cmd.widget
_log_filter_cmd.default
_log_filter_cmd.arg0
_log_filter_cmd.arg1
_log_filter_cmd.arg2
_log_filter_cmd.constraint
_log_filter_cmd.help
#
loop_
_settings.id
_settings.label
_settings.icon
_settings.widget
_settings.value
_settings.display
_settings.help
do_log_fs            "Laplacian of Gaussian Parameters"       bi-chat-right-text   fieldset   ?          show       ?
params_01            "Parameters"                             bi-chat-right-text   fieldset   ?          show       ?
params_05            "Parameters"                             bi-chat-right-text   fieldset   ?          show       ?
params_06            "Parameters"                             bi-chat-right-text   fieldset   ?          show       ?
params_07            "Parameters"                             bi-chat-right-text   fieldset   ?          show       ?
parallel_computing   "Parallel Computing"                     bi-chat-right-text   fieldset   ?          show       ?
#
loop_
_do_log_fs.id
_do_log_fs.label
_do_log_fs.widget
_do_log_fs.default
_do_log_fs.arg0
_do_log_fs.arg1
_do_log_fs.arg2
_do_log_fs.constraint
_do_log_fs.help
log_diam_min         "Min. diameter for LoG filter (A)"  range      200             50              500             10              ?               
; The smallest allowed diameter for the blob-detection algorithm.
This should correspond to the smallest size of your particles in Angstroms.
;
log_diam_max         "Max. diameter for LoG filter (A)"  range      250             50              500             10              ?               
; The largest allowed diameter for the blob-detection algorithm.
This should correspond to the largest size of your particles in Angstroms.
;
log_invert           "Are the particles white?"          bool       false           "?"             "?"             "?"             ?               
; Set this option to No if the particles are black, and to Yes if the particles are white.
;
#
loop_
_params_01.id
_params_01.label
_params_01.widget
_params_01.default
_params_01.arg0
_params_01.arg1
_params_01.arg2
_params_01.constraint
_params_01.help
log_maxres           "Maximum resolution to consider (A)" range      20              10              100             5               ?               
; The Laplacian-of-Gaussian filter will be applied to downscaled micrographs with the corresponding size.
Give a negative value to skip downscaling.
;
log_adjust_thr       "Adjust default threshold (stddev):" range      0               -1.0            1.0             0.05            ?               
; Use this to pick more (negative number -> lower threshold) or less (positive number -> higher threshold) particles compared to the default setting.
The threshold is moved this many standard deviations away from the average.
;
log_upper_thr        "Upper threshold (stddev):"         range      999.0           0.0             10.0            0.5             ?               
; Use this to discard picks with LoG thresholds that are this many standard deviations above the average, e.g.
to avoid high contrast contamination like ice and ethane droplets.
Good values depend on the contrast of micrographs and need to be interactively explored; for low contrast micrographs, values of ~ 1.5 may be reasonable, but the same value will be too low for high-contrast micrographs.
;
#
loop_
_params_05.id
_params_05.label
_params_05.widget
_params_05.default
_params_05.arg0
_params_05.arg1
_params_05.arg2
_params_05.constraint
_params_05.help
threshold_autopick   "Picking threshold:"                range      0.05            0               1.0             0.01            ?               
; Use lower thresholds to pick more particles (and more junk probably).

This option is ignored in the Laplacian-of-Gaussian picker.
Please use 'Adjust default threshold' in the 'Laplacian' tab instead.
;
mindist_autopick     "Minimum inter-particle distance (A):" range      100             0               1000            20              ?               
; Particles closer together than this distance will be consider to be a single cluster.
From each cluster, only one particle will be picked.


This option takes no effect for picking helical segments.
The inter-box distance is calculated with the number of asymmetrical units and the helical rise on 'Helix' tab.
This option is also ignored in the Laplacian-of-Gaussian picker.
The inter-box distance is calculated from particle diameters.
;
maxstddevnoise_autopick "Maximum stddev noise:"             range      1.1             0.9             1.5             0.02            ?               
; This is useful to prevent picking in carbon areas, or areas with big contamination features.
Peaks in areas where the background standard deviation in the normalized micrographs is higher than this value will be ignored.
Useful values are probably in the range 1.0 to 1.2.
Set to -1 to switch off the feature to eliminate peaks due to high background standard deviations.

This option is ignored in the Laplacian-of-Gaussian picker.
;
minavgnoise_autopick "Minimum avg noise:"                range      -999.0          -2              0.5             0.05            ?               
; This is useful to prevent picking in carbon areas, or areas with big contamination features.
Peaks in areas where the background standard deviation in the normalized micrographs is higher than this value will be ignored.
Useful values are probably in the range -0.5 to 0.
Set to -999 to switch off the feature to eliminate peaks due to low average background densities.

This option is ignored in the Laplacian-of-Gaussian picker.
;
#
loop_
_params_06.id
_params_06.label
_params_06.widget
_params_06.default
_params_06.arg0
_params_06.arg1
_params_06.arg2
_params_06.constraint
_params_06.help
do_write_fom_maps    "Write FOM maps?"                   bool       false           "?"             "?"             "?"             ?               
; If set to Yes, intermediate probability maps will be written out, which (upon reading them back in) will speed up tremendously the optimization of the threshold and inter-particle distance parameters.
However, with this option, one cannot run in parallel, as disc I/O is very heavy with this option set.
;
do_read_fom_maps     "Read FOM maps?"                    bool       false           "?"             "?"             "?"             ?               
; If written out previously, read the FOM maps back in and re-run the picking to quickly find the optimal threshold and inter-particle distance parameters
;
#
loop_
_params_07.id
_params_07.label
_params_07.widget
_params_07.default
_params_07.arg0
_params_07.arg1
_params_07.arg2
_params_07.constraint
_params_07.help
shrink               "Shrink factor:"                    range      0               0               1               0.1             ?               
; This is useful to speed up the calculations, and to make them less memory-intensive.
The micrographs will be downscaled (shrunk) to calculate the cross-correlations, and peak searching will be done in the downscaled FOM maps.
When set to 0, the micrographs will de downscaled to the lowpass filter of the references, a value between 0 and 1 will downscale the micrographs by that factor.
Note that the results will not be exactly the same when you shrink micrographs!

In the Laplacian-of-Gaussian picker, this option is ignored and the shrink factor always becomes 0.
;
#
loop_
_parallel_computing.id
_parallel_computing.label
_parallel_computing.widget
_parallel_computing.default
_parallel_computing.arg0
_parallel_computing.arg1
_parallel_computing.arg2
_parallel_computing.constraint
_parallel_computing.help
nr_mpi               "Number of MPI procs:"              range      {QSUB_NRMPI_VAL} 1               "{RELION_MPI_MAX}" 1               ?               
; Number of MPI nodes to use in parallel.
When set to 1, MPI will not be used.
The maximum can be set through the environment variable RELION_MPI_MAX.
;
#
loop_
_log.id
_log.label
_log.icon
_log.widget
_log.value
_log.display
_log.help
#
loop_
_dataviz.id
_dataviz.label
_dataviz.icon
_dataviz.widget
_dataviz.value
_dataviz.display
_dataviz.help
#
