TOGGLE_DEACTIVATE = 0

class Group:
    pass

def place(a,b,c=True,d=0,e=True):
    pass

is_tomo = False
group1 = group2 = group3 = group4 = 0

def initialiseImportWindow():
    grp = Group()
    place(grp,"do_raw", TOGGLE_DEACTIVATE, group1, False)
    grp.end()
    grp = Group()
    place(grp,"fn_in_raw")
    place(grp,"is_multiframe")
    grp.end()
    grp = Group()
    place(grp,"optics_group_name")
    place(grp,"fn_mtf")
    place(grp,"angpix")
    place(grp,"kV")
    place(grp,"Cs")
    place(grp,"Q0")
    place(grp,"beamtilt_x")
    place(grp,"beamtilt_y")
    place(grp,"do_other", TOGGLE_DEACTIVATE, group2, False)
    grp.end()
    grp = Group()
    place(grp,"fn_in_other")
    place(grp,"node_type")
    grp.end()
    grp = Group()
    place(grp,"optics_group_particles")

def initialiseMotioncorrWindow():
    grp = Group()
    place(grp,"input_star_mics", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    if not is_tomo:
            place(grp,"first_frame_sum", TOGGLE_DEACTIVATE)
    if not is_tomo:
    place(grp,"last_frame_sum", TOGGLE_DEACTIVATE)
    if not is_tomo:
    place(grp,"dose_per_frame", TOGGLE_DEACTIVATE)
    if not is_tomo:
    place(grp,"pre_exposure", TOGGLE_DEACTIVATE)
    place(grp,"eer_grouping", TOGGLE_DEACTIVATE)
    place(grp,"do_float16", TOGGLE_DEACTIVATE)
    if is_tomo:
    place(grp,"do_even_odd_split")
    grp.end()
    grp = Group()
    place(grp,"do_dose_weighting", TOGGLE_DEACTIVATE, group1)
    place(grp,"do_save_noDW", TOGGLE_DEACTIVATE)
    place(grp,"do_save_ps", TOGGLE_DEACTIVATE, group2)
    place(grp,"group_for_ps", TOGGLE_DEACTIVATE)
    place(grp,"bfactor", TOGGLE_DEACTIVATE)
    place2("patch_x", "patch_y", "Number of patches X, Y", TOGGLE_DEACTIVATE)
    place(grp,"group_frames", TOGGLE_DEACTIVATE)
    place(grp,"bin_factor", TOGGLE_DEACTIVATE)
    place(grp,"fn_gain_ref", TOGGLE_DEACTIVATE)
    place(grp,"gain_rot", TOGGLE_DEACTIVATE)
    place(grp,"gain_flip", TOGGLE_DEACTIVATE)
    place(grp,"fn_defect", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"do_own_motioncor", TOGGLE_DEACTIVATE, group4, True)
    place(grp,"fn_motioncor2_exe", TOGGLE_DEACTIVATE)
    place(grp,"gpu_ids")
    place(grp,"other_motioncor2_args", TOGGLE_DEACTIVATE)

def initialiseCtffindWindow():
    grp = Group()
    place(grp,"input_star_mics", TOGGLE_DEACTIVATE)
    if not is_tomo:
    place(grp,"use_noDW", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"do_phaseshift", TOGGLE_DEACTIVATE, group1)
    place3("phase_min", "phase_max", "phase_step", "Phase shift - Min, Max, Step (deg)", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"dast", TOGGLE_DEACTIVATE)
    place(grp,"fn_ctffind_exe", TOGGLE_DEACTIVATE)
    place(grp,"use_given_ps", TOGGLE_DEACTIVATE)
    place(grp,"slow_search", TOGGLE_DEACTIVATE)
    place(grp,"ctf_win", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"box", TOGGLE_DEACTIVATE)
    place(grp,"resmin", TOGGLE_DEACTIVATE)
    place(grp,"resmax", TOGGLE_DEACTIVATE)
    place(grp,"dfmin", TOGGLE_DEACTIVATE)
    place(grp,"dfmax", TOGGLE_DEACTIVATE)
    place(grp,"dfstep", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"localsearch_nominal_defocus", TOGGLE_DEACTIVATE)
    place(grp,"exp_factor_dose", TOGGLE_DEACTIVATE)

def initialiseManualpickWindow():
    grp = Group()
    place(grp,"fn_in", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place ("do_startend")
    grp.end()
    grp = Group()
    place(grp,"do_fom_threshold", TOGGLE_DEACTIVATE, group1)
    place(grp,"minimum_pick_fom", TOGGLE_DEACTIVATE)
    place(grp,"diameter")
    place(grp,"micscale")
    place(grp,"sigma_contrast")
    place(grp,"white_val")
    place(grp,"black_val")
    grp.end()
    grp = Group()
    place(grp,"lowpass")
    place(grp,"highpass")
    place(grp,"angpix")
    place(grp,"do_topaz_denoise", TOGGLE_DEACTIVATE)
    place(grp,"do_color", TOGGLE_LEAVE_ACTIVE, group3)
    place(grp,"color_label")
    place(grp,"fn_color")
    place(grp,"blue_value")
    place(grp,"red_value")

def initialiseAutopickWindow():
    grp = Group()
    place(grp,"fn_input_autopick", TOGGLE_DEACTIVATE)
    place(grp,"angpix", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"do_refs", TOGGLE_DEACTIVATE)
    place(grp,"do_log", TOGGLE_DEACTIVATE)
    place(grp,"do_topaz", TOGGLE_DEACTIVATE)
    place(grp,"continue_manual", TOGGLE_REACTIVATE)
    place(grp,"log_diam_min", TOGGLE_DEACTIVATE)
    place(grp,"log_diam_max", TOGGLE_DEACTIVATE)
    place(grp,"log_invert", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"log_maxres", TOGGLE_DEACTIVATE)
    place(grp,"log_adjust_thr")
    place(grp,"log_upper_thr")
    place(grp,"fn_topaz_exe", TOGGLE_DEACTIVATE)
    place(grp,"topaz_particle_diameter", TOGGLE_DEACTIVATE)
    current_y += STEPY/4
    place(grp,"do_topaz_train", TOGGLE_DEACTIVATE, group5)
    place(grp,"topaz_nr_particles", TOGGLE_DEACTIVATE)
    place(grp,"topaz_train_picks", TOGGLE_DEACTIVATE)
    place(grp,"do_topaz_train_parts", TOGGLE_DEACTIVATE, group6)
    place(grp,"topaz_train_parts", TOGGLE_DEACTIVATE)
    current_y += STEPY/4
    place(grp,"do_topaz_pick", TOGGLE_DEACTIVATE, group7)
    place(grp,"topaz_model", TOGGLE_DEACTIVATE)
    place(grp,"do_topaz_filaments", TOGGLE_DEACTIVATE, group8)
    place2("topaz_filament_threshold", "topaz_hough_length", "Threshold, Hough length (A)", TOGGLE_DEACTIVATE)
    current_y += STEPY/4
    place(grp,"topaz_other_args", TOGGLE_DEACTIVATE)
    place(grp,"fn_refs_autopick", TOGGLE_DEACTIVATE)
    place(grp,"do_ref3d", TOGGLE_DEACTIVATE, group1)
    place(grp,"fn_ref3d_autopick", TOGGLE_DEACTIVATE)
    place(grp,"ref3d_symmetry", TOGGLE_DEACTIVATE)
    place(grp,"ref3d_sampling", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"lowpass", TOGGLE_DEACTIVATE)
    place(grp,"highpass", TOGGLE_DEACTIVATE)
    place(grp,"angpix_ref", TOGGLE_DEACTIVATE)
    place(grp,"psi_sampling_autopick", TOGGLE_DEACTIVATE)
    place(grp,"do_invert_refs", TOGGLE_DEACTIVATE)
    place(grp,"do_ctf_autopick", TOGGLE_DEACTIVATE, group2)
    place(grp,"do_ignore_first_ctfpeak_autopick", TOGGLE_DEACTIVATE) # (current_y, "Ignore CTFs until first peak?", False,"Set this to Yes, only if this option was also used to generate the references.")
    place(grp,"threshold_autopick")
    place(grp,"mindist_autopick")
    place(grp,"maxstddevnoise_autopick")
    place(grp,"minavgnoise_autopick")
    grp.end()
    grp = Group()
    place(grp,"do_write_fom_maps")
    place(grp,"do_read_fom_maps")
    grp.end()
    grp = Group()
    place(grp,"shrink", TOGGLE_DEACTIVATE)
    place(grp,"use_gpu", TOGGLE_LEAVE_ACTIVE, group3)
    place(grp,"gpu_ids")
    place(grp,"do_pick_helical_segments", TOGGLE_DEACTIVATE, group4)
    place(grp,"helical_tube_outer_diameter")
    place(grp,"helical_tube_length_min")
    place(grp,"helical_tube_kappa_max")
    grp.end()
    grp = Group()
    place(grp,"helical_nr_asu")
    place(grp,"helical_rise")
    grp.end()
    grp = Group()
    place(grp,"do_amyloid")

def initialiseExtractWindow():
    grp = Group()
    place(grp,"star_mics", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"coords_suffix", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"do_reextract", TOGGLE_DEACTIVATE, group1)
    place(grp,"fndata_reextract", TOGGLE_DEACTIVATE)
    place(grp,"do_reset_offsets", TOGGLE_DEACTIVATE)
    place(grp,"do_recenter", TOGGLE_DEACTIVATE, group7)
    place3("recenter_x","recenter_y", "recenter_z", "Recenter on - X, Y, Z (pix):", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"do_float16", TOGGLE_DEACTIVATE)
    place(grp,"extract_size", TOGGLE_DEACTIVATE) # (current_y,"Particle box size (pix):", 128, 64, 512, 8, "Size of the extracted particles (in pixels). This should be an even number!")
    place(grp,"do_invert", TOGGLE_DEACTIVATE) # (current_y, "Invert contrast?", True, "If set to Yes, the contrast in the particles will be inverted.")
    grp.end()
    grp = Group()
    place(grp,"do_norm", TOGGLE_DEACTIVATE, group3)
    place(grp,"bg_diameter", TOGGLE_DEACTIVATE) # (current_y, "Diameter background circle (pix): ", -1, -1, 600, 10, "Particles will be normalized to a mean value of zero and a standard-deviation of one for all pixels in the background area.\
    place(grp,"white_dust", TOGGLE_DEACTIVATE) 
    # (current_y, "Stddev for white dust removal: ", -1, -1, 10, 0.1, "Remove very white pixels from the extracted particles. \
    # Pixels values higher than this many times the image stddev will be replaced with values from a Gaussian distribution. \n \n Use negative value to switch off dust removal.")
    place(grp,"black_dust", TOGGLE_DEACTIVATE) 
    # (current_y, "Stddev for black dust removal: ", -1, -1, 10, 0.1, "Remove very black pixels from the extracted particles. \
    # Pixels values higher than this many times the image stddev will be replaced with values from a Gaussian distribution. \n \n Use negative value to switch off dust removal.")
    grp.end()
    grp = Group()
    place(grp,"do_rescale", TOGGLE_DEACTIVATE, group4)
    place(grp,"rescale", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"do_fom_threshold", TOGGLE_DEACTIVATE, group7)
    place(grp,"minimum_pick_fom", TOGGLE_DEACTIVATE)
    place(grp,"do_extract_helix", TOGGLE_DEACTIVATE, group5)
    place(grp,"helical_tube_outer_diameter", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"helical_bimodal_angular_priors", TOGGLE_DEACTIVATE)
    grp.end()
    grp = Group()
    place(grp,"do_extract_helical_tubes", TOGGLE_DEACTIVATE, group6)
    place(grp,"do_cut_into_segments", TOGGLE_DEACTIVATE)
    place(grp,"helical_nr_asu", TOGGLE_DEACTIVATE)
    place(grp,"helical_rise", TOGGLE_DEACTIVATE)

def initialiseSelectWindow():
    grp = Group()
    place(grp,"fn_model", TOGGLE_DEACTIVATE)
    place(grp,"fn_mic", TOGGLE_DEACTIVATE)
    place(grp,"fn_data", TOGGLE_DEACTIVATE)
    place(grp,"do_class_ranker", TOGGLE_DEACTIVATE, group6)
    place(grp,"rank_threshold", TOGGLE_DEACTIVATE)
    place(grp,"select_nr_parts", TOGGLE_DEACTIVATE)
    place(grp,"select_nr_classes", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_recenter", TOGGLE_DEACTIVATE)
    place(grp,"do_regroup", TOGGLE_DEACTIVATE, group1)
    place(grp,"nr_groups", TOGGLE_DEACTIVATE)
    place(grp,"do_select_values", TOGGLE_DEACTIVATE, group3)
    place(grp,"select_label", TOGGLE_DEACTIVATE)
    place(grp,"select_minval", TOGGLE_DEACTIVATE)
    place(grp,"select_maxval", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_discard", TOGGLE_DEACTIVATE, group4)
    place(grp,"discard_label", TOGGLE_DEACTIVATE)
    place(grp,"discard_sigma", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_split", TOGGLE_DEACTIVATE, group5)
    place(grp,"do_random", TOGGLE_DEACTIVATE)
    place(grp,"split_size", TOGGLE_DEACTIVATE)
    place(grp,"nr_split", TOGGLE_DEACTIVATE)
    place(grp,"do_remove_duplicates", TOGGLE_DEACTIVATE, group2)
    place(grp,"duplicate_threshold", TOGGLE_DEACTIVATE)
    place(grp,"image_angpix", TOGGLE_DEACTIVATE)
    place(grp,"do_filaments", TOGGLE_DEACTIVATE, group3)
    place(grp,"dendrogram_threshold", TOGGLE_LEAVE_ACTIVE)
    place(grp,"dendrogram_minclass", TOGGLE_LEAVE_ACTIVE)

def initialiseClass2DWindow():
    grp = Group()
    place(grp,"fn_img", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"fn_cont", TOGGLE_REACTIVATE)
    place(grp,"do_ctf_correction", TOGGLE_DEACTIVATE, group1)
    place(grp,"ctf_intact_first_peak", TOGGLE_DEACTIVATE)
    place(grp,"nr_classes", TOGGLE_DEACTIVATE)
    place(grp,"tau_fudge")
    grp.end()
    grp =Group()
    place(grp,"do_em", TOGGLE_DEACTIVATE, group2)
    place(grp,"nr_iter_em")
    place(grp,"do_grad", TOGGLE_DEACTIVATE, group5)
    place(grp,"nr_iter_grad")
    grp.end()
    grp =Group()
    place(grp,"particle_diameter")
    place(grp,"do_zero_mask", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"highres_limit", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_center")
    place(grp,"dont_skip_align", TOGGLE_LEAVE_ACTIVE, group3)
    place(grp,"psi_sampling")
    place(grp,"offset_range")
    place(grp,"offset_step")
    grp.end()
    grp =Group()
    place(grp,"allow_coarser")
    place(grp,"do_helix", TOGGLE_DEACTIVATE, group4)
    place(grp,"helical_tube_outer_diameter")
    place(grp,"do_bimodal_psi")
    place(grp,"range_psi")
    place(grp,"do_restrict_xoff", TOGGLE_LEAVE_ACTIVE, group7)
    place(grp,"helical_rise", TOGGLE_LEAVE_ACTIVE)
    place(grp,"do_parallel_discio")
    place(grp,"nr_pool")
    place(grp,"do_preread_images", TOGGLE_LEAVE_ACTIVE, group5, True)
    place(grp,"scratch_dir")
    place(grp,"do_combine_thru_disc")
    grp.end()
    grp =Group()
    place(grp,"use_gpu", TOGGLE_LEAVE_ACTIVE, group6)
    place(grp,"gpu_ids", TOGGLE_LEAVE_ACTIVE)

def initialiseInimodelWindow():
    grp = Group()
    placeTomoInput(True, True, True, False)
    place(grp,"fn_img", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"fn_cont", TOGGLE_REACTIVATE)
    place(grp,"do_ctf_correction", TOGGLE_DEACTIVATE, group1)
    place(grp,"ctf_intact_first_peak", TOGGLE_DEACTIVATE)
    place(grp,"nr_iter")
    place(grp,"tau_fudge")
    place(grp,"nr_classes", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"particle_diameter")
    place(grp,"do_solvent", TOGGLE_DEACTIVATE)
    place(grp,"sym_name", TOGGLE_DEACTIVATE)
    place(grp,"do_run_C1", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"sigma_tilt", TOGGLE_DEACTIVATE)
    place(grp,"do_parallel_discio")
    place(grp,"nr_pool")
    place(grp,"do_preread_images", TOGGLE_LEAVE_ACTIVE, group5, True)
    place(grp,"scratch_dir")
    place(grp,"do_combine_thru_disc")
    grp.end()
    grp =Group()
    place(grp,"use_gpu", TOGGLE_LEAVE_ACTIVE, group6)
    place(grp,"gpu_ids", TOGGLE_LEAVE_ACTIVE)

def initialiseClass3DWindow():
    grp = Group()
    placeTomoInput(True, True, True, False)
    place(grp,"fn_img", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"fn_ref", TOGGLE_DEACTIVATE)
    place(grp,"fn_mask")
    grp.end()
    grp =Group()
    place(grp,"fn_cont", TOGGLE_REACTIVATE)
    place(grp,"ref_correct_greyscale", TOGGLE_DEACTIVATE)
    place(grp,"trust_ref_size", TOGGLE_DEACTIVATE)
    place(grp,"ini_high", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"sym_name", TOGGLE_DEACTIVATE)
    place(grp,"do_ctf_correction", TOGGLE_DEACTIVATE, group1)
    place(grp,"ctf_intact_first_peak", TOGGLE_DEACTIVATE)
    place(grp,"nr_classes", TOGGLE_DEACTIVATE)
    place(grp,"tau_fudge")
    grp.end()
    grp =Group()
    place(grp,"nr_iter")
    place(grp,"do_fast_subsets", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"particle_diameter")
    place(grp,"do_zero_mask", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"highres_limit", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_blush", TOGGLE_DEACTIVATE)
    place(grp,"dont_skip_align", TOGGLE_LEAVE_ACTIVE, group3)
    place(grp,"sampling")
    place(grp,"offset_range")
    place(grp,"offset_step")
    place(grp,"do_local_ang_searches", TOGGLE_LEAVE_ACTIVE, group4)
    place(grp,"sigma_angles")
    place(grp,"relax_sym")
    grp.end()
    grp =Group()
    place(grp,"allow_coarser")
    grp.end()
    grp =Group()
    place(grp,"sigma_tilt", TOGGLE_DEACTIVATE)
    # helix_text", TOGGLE_DEACTIVATE) # (current_y, "Nov 21, 2015")
    place(grp,"do_helix", TOGGLE_DEACTIVATE, group5)
    place2("helical_tube_inner_diameter", "helical_tube_outer_diameter", "Tube diameter - inner, outer (A):", TOGGLE_DEACTIVATE)
    place3("range_rot", "range_tilt", "range_psi", "Angular search range - rot, tilt, psi (deg):", TOGGLE_DEACTIVATE)
    place(grp,"helical_range_distance", TOGGLE_DEACTIVATE)
    place(grp,"keep_tilt_prior_fixed", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_apply_helical_symmetry", TOGGLE_DEACTIVATE, group8)
    place(grp,"helical_nr_asu", TOGGLE_DEACTIVATE)
    place2("helical_twist_initial", "helical_rise_initial", "Initial twist (deg), rise (A):", TOGGLE_DEACTIVATE)
    place(grp,"helical_z_percentage", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_local_search_helical_symmetry", TOGGLE_DEACTIVATE, group6)
    place3("helical_twist_min","helical_twist_max", "helical_twist_inistep", "Twist search - Min, Max, Step (deg):", TOGGLE_DEACTIVATE)
    place3("helical_rise_min", "helical_rise_max", "helical_rise_inistep", "Rise search - Min, Max, Step (A):", TOGGLE_DEACTIVATE)
    place(grp,"do_parallel_discio")
    place(grp,"nr_pool")
    place(grp,"do_pad1")
    place(grp,"do_preread_images", TOGGLE_LEAVE_ACTIVE, group7, True)
    place(grp,"scratch_dir")
    place(grp,"do_combine_thru_disc")
    grp.end()
    grp =Group()
    place(grp,"use_gpu", TOGGLE_LEAVE_ACTIVE, group8)
    place(grp,"gpu_ids")

def initialiseAutorefineWindow():
    grp = Group()
    placeTomoInput(True, True, True, False)
    place(grp,"fn_img", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"fn_ref", TOGGLE_DEACTIVATE)
    place(grp,"fn_mask")
    grp.end()
    grp =Group()
    place(grp,"fn_cont", TOGGLE_REACTIVATE)
    place(grp,"ref_correct_greyscale", TOGGLE_DEACTIVATE)
    place(grp,"trust_ref_size", TOGGLE_DEACTIVATE)
    place(grp,"ini_high", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"sym_name", TOGGLE_DEACTIVATE)
    place(grp,"do_ctf_correction", TOGGLE_DEACTIVATE, group1)
    place(grp,"ctf_intact_first_peak", TOGGLE_DEACTIVATE)
    place(grp,"particle_diameter")
    place(grp,"do_zero_mask", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_solvent_fsc")
    grp.end()
    grp =Group()
    place(grp,"do_blush", TOGGLE_DEACTIVATE)
    place(grp,"sampling", TOGGLE_DEACTIVATE)
    place(grp,"offset_range", TOGGLE_DEACTIVATE)
    place(grp,"offset_step", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"auto_local_sampling", TOGGLE_DEACTIVATE)
    place(grp,"relax_sym")
    grp.end()
    grp =Group()
    place(grp,"auto_faster")
    grp.end()
    grp =Group()
    place(grp,"sigma_tilt", TOGGLE_DEACTIVATE)
    place(grp,"do_helix", TOGGLE_DEACTIVATE, group2)
    place2("helical_tube_inner_diameter", "helical_tube_outer_diameter", "Tube diameter - inner, outer (A):",TOGGLE_DEACTIVATE)
    place3("range_rot", "range_tilt", "range_psi", "Angular search range - rot, tilt, psi (deg):", TOGGLE_DEACTIVATE)
    place(grp,"helical_range_distance", TOGGLE_DEACTIVATE)
    place(grp,"keep_tilt_prior_fixed", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_apply_helical_symmetry", TOGGLE_DEACTIVATE, group5)
    place(grp,"helical_nr_asu", TOGGLE_DEACTIVATE)
    place2("helical_twist_initial", "helical_rise_initial", "Initial twist (deg), rise (A):",TOGGLE_DEACTIVATE)
    place(grp,"helical_z_percentage", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_local_search_helical_symmetry", TOGGLE_DEACTIVATE, group3)
    place3("helical_twist_min", "helical_twist_max", "helical_twist_inistep", "Twist search - Min, Max, Step (deg):", TOGGLE_DEACTIVATE)
    place3("helical_rise_min", "helical_rise_max","helical_rise_inistep","Rise search - Min, Max, Step (A):", TOGGLE_DEACTIVATE)
    place(grp,"do_parallel_discio")
    place(grp,"nr_pool")
    place(grp,"do_pad1")
    place(grp,"do_preread_images", TOGGLE_LEAVE_ACTIVE, group4, True)
    place(grp,"scratch_dir")
    place(grp,"do_combine_thru_disc")
    grp.end()
    grp =Group()
    place(grp,"use_gpu", TOGGLE_LEAVE_ACTIVE, group5)
    place(grp,"gpu_ids")

def initialiseMultiBodyWindow():
    grp = Group()
    place(grp,"fn_in", TOGGLE_DEACTIVATE)
    place(grp,"fn_cont", TOGGLE_REACTIVATE)
    place(grp,"fn_bodies", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_subtracted_bodies", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_blush", TOGGLE_DEACTIVATE)
    place(grp,"sampling", TOGGLE_DEACTIVATE)
    place(grp,"offset_range", TOGGLE_DEACTIVATE)
    place(grp,"offset_step", TOGGLE_DEACTIVATE)
    place(grp,"do_analyse", TOGGLE_LEAVE_ACTIVE, group5)
    place(grp,"nr_movies")
    place(grp,"do_select", TOGGLE_LEAVE_ACTIVE, group6)
    place(grp,"select_eigenval")
    place(grp,"eigenval_min")
    place(grp,"eigenval_max")
    place(grp,"do_parallel_discio")
    place(grp,"nr_pool")
    place(grp,"do_pad1")
    place(grp,"do_preread_images", TOGGLE_LEAVE_ACTIVE, group7, True)
    place(grp,"scratch_dir")
    place(grp,"do_combine_thru_disc")
    grp.end()
    grp =Group()
    place(grp,"use_gpu", TOGGLE_LEAVE_ACTIVE, group4)
    place(grp,"gpu_ids")

def initialiseMaskcreateWindow():
    grp = Group()
    place(grp,"fn_in", TOGGLE_DEACTIVATE) # (current_y, "Input 3D map:", NODE_3DREF, "", "MRC map files (*.mrc)", "Provide an input MRC map from which to start binarizing the map.")
    place(grp,"lowpass_filter")
    place(grp,"angpix")
    grp.end()
    grp =Group()
    place(grp,"inimask_threshold")
    place(grp,"extend_inimask")
    place(grp,"width_mask_edge")
    place(grp,"do_helix", TOGGLE_LEAVE_ACTIVE, group1)
    place(grp,"helical_z_percentage")

def initialiseJoinstarWindow():
    grp = Group()
    place(grp,"do_part", TOGGLE_DEACTIVATE, group1)
    place(grp,"fn_part1", TOGGLE_DEACTIVATE)
    place(grp,"fn_part2", TOGGLE_DEACTIVATE)
    place(grp,"fn_part3", TOGGLE_DEACTIVATE)
    place(grp,"fn_part4", TOGGLE_DEACTIVATE)
    place(grp,"do_mic", TOGGLE_DEACTIVATE, group2)
    place(grp,"fn_mic1", TOGGLE_DEACTIVATE)
    place(grp,"fn_mic2", TOGGLE_DEACTIVATE)
    place(grp,"fn_mic3", TOGGLE_DEACTIVATE)
    place(grp,"fn_mic4", TOGGLE_DEACTIVATE)
    place(grp,"do_mov", TOGGLE_DEACTIVATE, group3) # (current_y, "Combine movie STAR files?", False, "", mov_group)
    place(grp,"fn_mov1", TOGGLE_DEACTIVATE)
    place(grp,"fn_mov2", TOGGLE_DEACTIVATE)
    place(grp,"fn_mov3", TOGGLE_DEACTIVATE)
    place(grp,"fn_mov4", TOGGLE_DEACTIVATE)

def initialiseSubtractWindow():
    grp = Group()
    place(grp,"fn_opt", TOGGLE_DEACTIVATE)
    place(grp,"fn_mask", TOGGLE_DEACTIVATE)
    place(grp,"do_data", TOGGLE_DEACTIVATE, group1)
    place(grp,"fn_data", TOGGLE_DEACTIVATE)
    place(grp,"do_float16", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_fliplabel", TOGGLE_DEACTIVATE, group2)
    place(grp,"fn_fliplabel", TOGGLE_DEACTIVATE)
    place(grp,"do_center_mask", TOGGLE_DEACTIVATE, group3, True)
    place(grp,"do_center_xyz", TOGGLE_DEACTIVATE, group4)
    place3("center_x", "center_y", "center_z", "Center coordinate - X, Y, Z (pix):", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"new_box", TOGGLE_DEACTIVATE)

def initialisePostprocessWindow():
    grp = Group()
    place(grp,"fn_in", TOGGLE_DEACTIVATE) # (current_y, "One of the 2 unfiltered half-maps:", NODE_HALFMAP, "", "MRC map files (*half1_class001_unfil.mrc)",  "Provide one of the two unfiltered half-reconstructions that were output upon convergence of a 3D auto-refine run.")
    place(grp,"fn_mask", TOGGLE_DEACTIVATE) # (current_y, "Solvent mask:", NODE_MASK, "", "Image Files (*.{spi,vol,msk,mrc})", "Provide a soft mask where the protein is white (1) and the solvent is black (0). Often, the softer the mask the higher resolution estimates you will get. A soft edge of 5-10 pixels is often a good edge width.")
    grp.end()
    grp =Group()
    place(grp,"angpix")
    place(grp,"do_auto_bfac", TOGGLE_LEAVE_ACTIVE, group1)
    place(grp,"autob_lowres")
    place(grp,"do_adhoc_bfac", TOGGLE_LEAVE_ACTIVE, group2)
    place(grp,"adhoc_bfac")
    grp.end()
    grp =Group()
    place(grp,"do_skip_fsc_weighting", TOGGLE_LEAVE_ACTIVE, group3)
    place(grp,"low_pass")
    grp.end()
    grp =Group()
    place(grp,"fn_mtf")
    place(grp,"mtf_angpix")

def initialiseLocresWindow():
    grp = Group()
    place(grp,"fn_in", TOGGLE_DEACTIVATE)
    place(grp,"fn_mask")
    grp.end()
    grp =Group()
    place(grp,"angpix", TOGGLE_DEACTIVATE)
    place(grp,"do_resmap_locres", TOGGLE_DEACTIVATE, group1)
    place(grp,"fn_resmap", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"pval", TOGGLE_DEACTIVATE)
    place(grp,"minres", TOGGLE_DEACTIVATE)
    place(grp,"maxres", TOGGLE_DEACTIVATE)
    place(grp,"stepres", TOGGLE_DEACTIVATE)
    place(grp,"do_relion_locres", TOGGLE_DEACTIVATE, group2)
    # place(grp,"locres_sampling", TOGGLE_DEACTIVATE)
    # place(grp,"randomize_at", TOGGLE_DEACTIVATE)
    # current_y += STEPY /2 
    place(grp,"adhoc_bfac", TOGGLE_DEACTIVATE)
    place(grp,"fn_mtf", TOGGLE_DEACTIVATE)

def initialiseMotionrefineWindow():
    grp = Group()
    place(grp,"fn_mic", TOGGLE_DEACTIVATE)
    place(grp,"fn_data", TOGGLE_DEACTIVATE)
    place(grp,"fn_post", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"first_frame", TOGGLE_DEACTIVATE)
    place(grp,"last_frame", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"extract_size", TOGGLE_DEACTIVATE)
    place(grp,"rescale", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_float16", TOGGLE_DEACTIVATE)
    place(grp,"do_param_optim", TOGGLE_LEAVE_ACTIVE, group2)
    place(grp,"eval_frac")
    place(grp,"optim_min_part")
    place(grp,"do_polish", TOGGLE_DEACTIVATE, group1)
    current_y += STEPY /2 
    place(grp,"opt_params", TOGGLE_DEACTIVATE)
    place(grp,"do_own_params", TOGGLE_DEACTIVATE, group4)
    place(grp,"sigma_vel", TOGGLE_DEACTIVATE)
    place(grp,"sigma_div", TOGGLE_DEACTIVATE)
    place(grp,"sigma_acc", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"minres", TOGGLE_DEACTIVATE)
    place(grp,"maxres", TOGGLE_DEACTIVATE)

def initialiseCtfrefineWindow():
    grp = Group()
    place(grp,"fn_data", TOGGLE_DEACTIVATE)
    place(grp,"fn_post", TOGGLE_DEACTIVATE)
    place(grp,"do_aniso_mag", TOGGLE_LEAVE_ACTIVE, group3, True) # True means: activating aniso_mag will deactive higher-order aberrations
    current_y += STEPY /2 
    place(grp,"do_ctf", TOGGLE_LEAVE_ACTIVE, group1)
    place(grp,"do_defocus", TOGGLE_LEAVE_ACTIVE)
    place(grp,"do_astig", TOGGLE_LEAVE_ACTIVE)
    place(grp,"do_bfactor", TOGGLE_LEAVE_ACTIVE)
    place(grp,"do_phase", TOGGLE_LEAVE_ACTIVE)
    current_y += STEPY /2 
    place(grp,"do_tilt", TOGGLE_LEAVE_ACTIVE, group4)
    place(grp,"do_trefoil", TOGGLE_LEAVE_ACTIVE)
    current_y += STEPY /2 
    place(grp,"do_4thorder", TOGGLE_LEAVE_ACTIVE)
    current_y += STEPY /2 
    place(grp,"minres", TOGGLE_DEACTIVATE)

def initialiseDynaMightWindow():
    grp = Group()
    place(grp,"fn_star", TOGGLE_DEACTIVATE)
    place(grp,"fn_map", TOGGLE_DEACTIVATE)
    # place(grp,"fn_mask", TOGGLE_DEACTIVATE)
     current_y += STEPY /2 
    place(grp,"nr_gaussians", TOGGLE_DEACTIVATE)
    place(grp,"initial_threshold", TOGGLE_DEACTIVATE)
    place(grp,"reg_factor", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"fn_dynamight_exe", TOGGLE_DEACTIVATE)
    place(grp,"gpu_id")
    place(grp,"do_preload")
    place(grp,"fn_checkpoint", TOGGLE_REACTIVATE)
    current_y += STEPY /2 
    place(grp,"do_visualize", TOGGLE_REACTIVATE, group1, False)
    place(grp,"halfset")
    current_y += STEPY /2 
    place(grp,"do_inverse", TOGGLE_REACTIVATE, group2, False)
    place(grp,"nr_epochs")
    place(grp,"do_store_deform")
    current_y += STEPY /2 
    place(grp,"do_reconstruct",TOGGLE_REACTIVATE, group3, False)
    place(grp,"backproject_batchsize")

def initialiseModelAngeloWindow():
    grp = Group()
    place(grp,"fn_map", TOGGLE_DEACTIVATE)
    place(grp,"p_seq", TOGGLE_DEACTIVATE)
    place(grp,"d_seq", TOGGLE_DEACTIVATE)
    place(grp,"r_seq", TOGGLE_DEACTIVATE)
     current_y += STEPY /2 
    place(grp,"fn_modelangelo_exe", TOGGLE_DEACTIVATE)
    place(grp,"gpu_id", TOGGLE_DEACTIVATE)
    place(grp,"do_hhmer", TOGGLE_LEAVE_ACTIVE, group1, False)
    current_y += STEPY /2 
    place(grp,"fn_lib", TOGGLE_LEAVE_ACTIVE)
    place(grp,"alphabet", TOGGLE_LEAVE_ACTIVE)
    current_y += STEPY /2 
    place(grp,"F1", TOGGLE_LEAVE_ACTIVE)
    place(grp,"F2", TOGGLE_LEAVE_ACTIVE)
    place(grp,"F3", TOGGLE_LEAVE_ACTIVE)
    place(grp,"E", TOGGLE_LEAVE_ACTIVE)

def initialiseExternalWindow():
    grp = Group()
    place(grp,"fn_exe", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"in_mov", TOGGLE_DEACTIVATE)
    place(grp,"in_mic", TOGGLE_DEACTIVATE)
    place(grp,"in_part", TOGGLE_DEACTIVATE)
    place(grp,"in_coords", TOGGLE_DEACTIVATE)
    place(grp,"in_3dref", TOGGLE_DEACTIVATE)
    place(grp,"in_mask", TOGGLE_DEACTIVATE)
    place2("param1_label", "param1_value", "Param1 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param2_label", "param2_value", "Param2 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param3_label", "param3_value", "Param3 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param4_label", "param4_value", "Param4 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param5_label", "param5_value", "Param5 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param6_label", "param6_value", "Param6 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param7_label", "param7_value", "Param7 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param8_label", "param8_value", "Param8 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param9_label", "param9_value", "Param9 label, value:", TOGGLE_LEAVE_ACTIVE)
    place2("param10_label", "param10_value", "Param10 label, value:", TOGGLE_LEAVE_ACTIVE)

def placeTomoInput(bool has_tomograms, bool has_particles,
    place(grp,"in_optimisation", TOGGLE_DEACTIVATE)
    place(grp,"use_direct_entries", TOGGLE_DEACTIVATE, group0, False)
    if (has_particles) place(grp,"in_particles", TOGGLE_DEACTIVATE)
    if (has_tomograms) place(grp,"in_tomograms", TOGGLE_DEACTIVATE)
    if (has_trajectories) place(grp,"in_trajectories", TOGGLE_DEACTIVATE)
    if (has_manifolds) place(grp,"in_manifolds", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 

def initialiseTomoImportWindow():
    grp = Group()
    place(grp,"movie_files", TOGGLE_DEACTIVATE)
    place(grp,"images_are_motion_corrected", TOGGLE_DEACTIVATE)
    place(grp,"mdoc_files", TOGGLE_DEACTIVATE)
    place(grp,"optics_group_name", TOGGLE_DEACTIVATE)
    place(grp,"prefix", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"angpix", TOGGLE_DEACTIVATE)
    place(grp,"kV", TOGGLE_DEACTIVATE)
    place(grp,"Cs", TOGGLE_DEACTIVATE)
    place(grp,"Q0", TOGGLE_DEACTIVATE)
    place(grp,"dose_rate", TOGGLE_DEACTIVATE)
    place(grp,"dose_is_per_movie_frame", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"tilt_axis_angle", TOGGLE_DEACTIVATE)
    place(grp,"mtf_file", TOGGLE_DEACTIVATE)
    place(grp,"flip_tiltseries_hand", TOGGLE_DEACTIVATE)
    place(grp,"do_coords", TOGGLE_DEACTIVATE, group1, False)
    place(grp,"in_coords", TOGGLE_DEACTIVATE)
    place(grp,"remove_substring", TOGGLE_DEACTIVATE)
    place(grp,"remove_substring2", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"is_center", TOGGLE_DEACTIVATE, group2, False)
    place(grp,"scale_factor", TOGGLE_DEACTIVATE)
    place(grp,"add_factor", TOGGLE_DEACTIVATE)

def initialiseTomoAlignTiltseriesWindow():
    grp = Group()
    place(grp,"in_tiltseries", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"tomogram_thickness", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"fn_batchtomo_exe", TOGGLE_DEACTIVATE)
    place(grp,"fn_aretomo_exe", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_imod_fiducials", TOGGLE_DEACTIVATE, group1, False)
    place(grp,"fiducial_diameter", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_imod_patchtrack", TOGGLE_DEACTIVATE, group2, False)
    place(grp,"patch_size", TOGGLE_DEACTIVATE)
    place(grp,"patch_overlap", TOGGLE_DEACTIVATE)
    place(grp,"do_aretomo2", TOGGLE_DEACTIVATE, group3, False)
    grp.end()
    grp =Group()
    place(grp,"do_aretomo_tiltcorrect", TOGGLE_DEACTIVATE, group4, False)
    place(grp,"aretomo_tiltcorrect_angle", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"do_aretomo_ctf", TOGGLE_DEACTIVATE, group5, False)
    place(grp,"do_aretomo_phaseshift", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"other_aretomo_args", TOGGLE_DEACTIVATE)
    place(grp,"gpu_ids")

def initialiseTomoReconstructTomogramsWindow():
    grp = Group()
    place(grp,"in_tiltseries", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"generate_split_tomograms", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"do_proj", TOGGLE_DEACTIVATE, group1, False)
    place(grp,"centre_proj", TOGGLE_DEACTIVATE)
    place(grp,"thickness_proj", TOGGLE_DEACTIVATE)
    place(grp,"xdim", TOGGLE_DEACTIVATE)
    place(grp,"ydim", TOGGLE_DEACTIVATE)
    place(grp,"zdim", TOGGLE_DEACTIVATE)
    place(grp,"binned_angpix", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place ("tiltangle_offset", TOGGLE_DEACTIVATE)
    place(grp,"tomo_name")
    current_y += STEPY /2 
    place(grp,"do_fourier", TOGGLE_DEACTIVATE, group2, False)
    place(grp,"ctf_intact_first_peak", TOGGLE_DEACTIVATE)

def initialiseTomoDenoiseTomogramsWindow():
    grp = Group()
    place(grp,"in_tomoset", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"cryocare_path")
    place(grp,"gpu_ids")
    place(grp,"do_cryocare_train", TOGGLE_DEACTIVATE, group1, False)
    current_y += STEPY /2 
    place(grp,"tomograms_for_training", TOGGLE_DEACTIVATE)
    place(grp,"number_training_subvolumes", TOGGLE_DEACTIVATE)
    place(grp,"subvolume_dimensions", TOGGLE_DEACTIVATE)
    place(grp,"do_cryocare_predict", TOGGLE_DEACTIVATE, group2, False)
    current_y += STEPY /2 
    place(grp,"care_denoising_model", TOGGLE_DEACTIVATE)
    place3("ntiles_x", "ntiles_y", "ntiles_z", "Number of tiles in X,Y,Z:", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"denoising_tomo_name", TOGGLE_DEACTIVATE)

def initialiseTomoPickTomogramsWindow():
    grp = Group()
    place(grp,"in_tomoset", TOGGLE_DEACTIVATE)
    # place(grp,"cache_size", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"pick_mode", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"particle_spacing", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"in_star_file", TOGGLE_DEACTIVATE)

def initialiseTomoSubtomoWindow():
    grp = Group()
    placeTomoInput(True, True, True, False)
    place(grp,"binning", TOGGLE_DEACTIVATE)
    place(grp,"box_size", TOGGLE_DEACTIVATE)
    place(grp,"crop_size", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place ("max_dose", TOGGLE_DEACTIVATE)
    place ("min_frames", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"do_stack2d", TOGGLE_DEACTIVATE)
    place(grp,"do_float16", TOGGLE_DEACTIVATE)

def initialiseTomoCtfRefineWindow():
    grp = Group()
    placeTomoInput(True, True, True, False)
    place(grp,"in_halfmaps", TOGGLE_DEACTIVATE)
    place(grp,"in_refmask", TOGGLE_DEACTIVATE)
    place(grp,"in_post", TOGGLE_DEACTIVATE)
    place(grp,"box_size", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"do_defocus", TOGGLE_DEACTIVATE, group1)
    place(grp,"focus_range", TOGGLE_DEACTIVATE)
    place(grp,"do_reg_def", TOGGLE_DEACTIVATE, group2)
    place(grp,"lambda", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"do_scale", TOGGLE_DEACTIVATE, group3)
    place(grp,"do_frame_scale", TOGGLE_DEACTIVATE)
    place(grp,"do_tomo_scale", TOGGLE_DEACTIVATE)
    place(grp,"do_odd_aberr", TOGGLE_DEACTIVATE, group3)
    place(grp,"nr_odd_aberr", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"do_even_aberr", TOGGLE_DEACTIVATE, group4)
    place(grp,"nr_even_aberr", TOGGLE_DEACTIVATE)

def initialiseTomoAlignWindow():
    grp = Group()
    placeTomoInput(True, True, True, False)
    place(grp,"in_halfmaps", TOGGLE_DEACTIVATE)
    place(grp,"in_refmask", TOGGLE_DEACTIVATE)
    place(grp,"in_post", TOGGLE_DEACTIVATE)
    place(grp,"box_size", TOGGLE_DEACTIVATE)
    place(grp,"max_error", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"do_shift_align", TOGGLE_DEACTIVATE, group3)
    place(grp,"shift_align_type", TOGGLE_DEACTIVATE)
    place(grp,"do_motion", TOGGLE_DEACTIVATE, group2)
    current_y += STEPY /2 
    place(grp,"sigma_vel", TOGGLE_DEACTIVATE)
    place(grp,"sigma_div", TOGGLE_DEACTIVATE)
    place(grp,"do_sq_exp_ker", TOGGLE_DEACTIVATE)

def initialiseTomoReconParWindow():
    grp = Group()
    placeTomoInput(True, True, True, False)
    place(grp,"binning", TOGGLE_DEACTIVATE)
    place(grp,"box_size", TOGGLE_DEACTIVATE)
    place(grp,"crop_size", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"snr", TOGGLE_DEACTIVATE)
    current_y += STEPY /2 
    place(grp,"sym_name", TOGGLE_DEACTIVATE)
    place(grp,"do_helix", TOGGLE_DEACTIVATE, group1)
    current_y += STEPY /2 
    place(grp,"helical_nr_asu")
    place(grp,"helical_twist")
    place(grp,"helical_rise")
    place(grp,"helical_tube_outer_diameter")
    place(grp,"helical_z_percentage")

def initialiseTomoExcludeTiltImagesWindow():
    grp = Group()
    place(grp,"in_tiltseries", TOGGLE_DEACTIVATE)
    grp.end()
    grp =Group()
    place(grp,"cache_size", TOGGLE_DEACTIVATE)
