void RelionJob::initialiseSelectJob()
{
	hidden_name = ".gui_select";

	joboptions["fn_model"] = JobOption("Select classes from job:", LABEL_OPTIMISER_CPIPE, 1, "", "STAR files (*_optimiser.star)", "A _optimiser.star (or for backwards compatibility also a _model.star) file from a previous 2D or 3D classification run to select classes from.");
	joboptions["fn_mic"] = JobOption("OR select from micrographs.star:", LABEL_MICS_CPIPE, 1, "", "STAR files (*.star)", "A micrographs.star file to select micrographs from.");
	joboptions["fn_data"] = JobOption("OR select from particles.star:", LABEL_PARTS_CPIPE, 1, "", "STAR files (*.star)", "A particles.star file to select individual particles from.");

	joboptions["do_class_ranker"] = JobOption("Automatically select 2D classes?", false, "If set to True, the class_ranker program will be used to make an automated class selection, based on the parameters below. This option only works when selecting classes from a relion_refine job (input optimiser.star on the I.O tab)");
	joboptions["rank_threshold"] = JobOption("Minimum threshold for auto-selection: ", 0.5, 0, 1, 0.05, "Only classes with a pre dicted threshold above this value will be selected.");
	joboptions["select_nr_parts"] = JobOption("Select at least this many particles: ", -1, -1, 10000, 500, "Even if they have scores below the minimum threshold, select at least this many particles with the best scores.");
	joboptions["select_nr_classes"] = JobOption("OR: select at least this many classes: ", -1, -1, 24, 1, "Even if they have scores below the minimum threshold, select at least this many classes with the best scores.");

	joboptions["do_recenter"] = JobOption("Re-center the class averages?", false, "This option is only used when selecting particles from 2D classes. The selected class averages will all re-centered on their center-of-mass. This is useful when you plane to use these class averages as templates for auto-picking.");
	joboptions["do_regroup"] = JobOption("Regroup the particles?", false, "If set to Yes, then the program will regroup the selected particles in 'more-or-less' the number of groups indicated below. For re-grouping from individual particle _data.star files, a _model.star file with the same prefix should exist, i.e. the particle star file should be generated by relion_refine");
	joboptions["nr_groups"] = JobOption("Approximate nr of groups: ", 1, 50, 20, 1, "It is normal that the actual number of groups may deviate a little from this number. ");

	joboptions["do_select_values"] = JobOption("Select based on metadata values?", false, "If set to Yes, the job will be non-interactive and the selected star file will be based only on the value of the corresponding metadata label. Note that this option is only valid for micrographs or particles STAR files.");
	joboptions["select_label"] = JobOption("Metadata label for subset selection:", (std::string)"rlnCtfMaxResolution", "This column from the input STAR file will be used for the subset selection.");
	joboptions["select_minval"] = JobOption("Minimum metadata value:",  (std::string)"-9999.", "Only lines in the input STAR file with the corresponding metadata value larger than or equal to this value will be included in the subset.");
	joboptions["select_maxval"] = JobOption("Maximum metadata value:",  (std::string)"9999.", "Only lines in the input STAR file with the corresponding metadata value smaller than or equal to this value will be included in the subset.");

	joboptions["do_discard"] = JobOption("OR: select on image statistics?", false, "If set to Yes, the job will be non-interactive and all images in the input star file that have average and/or stddev pixel values that are more than the specified sigma-values away from the ensemble mean will be discarded.");
	joboptions["discard_label"] = JobOption("Metadata label for images:", (std::string)"rlnImageName", "Specify which column from the input STAR contains the names of the images to be used to calculate the average and stddev values.");
	joboptions["discard_sigma"] = JobOption("Sigma-value for discarding images:", 4, 1, 10, 0.1, "Images with average and/or stddev values that are more than this many times the ensemble stddev away from the ensemble mean will be discarded.");

	joboptions["do_split"] = JobOption("OR: split into subsets?", false, "If set to Yes, the job will be non-interactive and the star file will be split into subsets as defined below.");
	joboptions["do_random"] = JobOption("Randomise order before making subsets?:", false, "If set to Yes, the input STAR file order will be randomised. If set to No, the original order in the input STAR file will be maintained.");
	joboptions["split_size"] = JobOption("Subset size: ", 100, 100, 10000, 100, "The number of lines in each of the output subsets. When this is -1, items are divided into a number of subsets specified in the next option.");
	joboptions["nr_split"] = JobOption("OR: number of subsets: ", -1, 1, 50, 1, "Give a positive integer to specify into how many equal-sized subsets the data will be divided. When the subset size is also specified, only this number of subsets, each with the specified size, will be written, possibly missing some items. When this is -1, all items are used, generating as many subsets as necessary.");

	joboptions["do_remove_duplicates"] = JobOption("OR: remove duplicates?", false, "If set to Yes, duplicated particles that are within a given distance are removed leaving only one. Duplicated particles are sometimes generated when particles drift into the same position during alignment. They inflate and invalidate gold-standard FSC calculation.");
	joboptions["duplicate_threshold"] = JobOption("Minimum inter-particle distance (A)", 30, 0, 1000, 1, "Particles within this distance are removed leaving only one.");
	joboptions["image_angpix"] = JobOption("Pixel size before extraction (A)", -1, -1, 10, 0.01, "The pixel size of particles (relevant to rlnOriginX/Y) is read from the STAR file. When the pixel size of the original micrograph used for auto-picking and extraction (relevant to rlnCoordinateX/Y) is different, specify it here. In other words, this is the pixel size after binning during motion correction, but before down-sampling during extraction.");

	joboptions["do_filaments"] = JobOption("OR: select filaments by dendrogram?", false, "If set to Yes, then the FilamentTools program by David Li will be used to perform a hierarchical clustering of the filaments, based on 2D class average assignments of their individual segments.");
	joboptions["dendrogram_threshold"] = JobOption("Dendrogram threshold: ", 0.85, 0, 1, 0.05, "Lower thresholds will produce more clusters; After the dendrogram has been calculated in the initial running of this job, subsequent continuation jobs can quickly test other threshold values. The output logfile.pdf can be visualised to follow the process until a good threshold has been achieved.");
	joboptions["dendrogram_minclass"] = JobOption("Minimum class size: ", -1000, -1000, 50000, 1000, "If set to a positive value, then particle star files with clusters that have at least this number of particles will be written out. Keep th default negative value for faster testing of the threshold.");
}

bool RelionJob::getCommandsSelectJob(std::string &outputname, std::vector<std::string> &commands,
		std::string &final_command, bool do_makedir, int job_counter, std::string &error_message)
{
	commands.clear();
	initialisePipeline(outputname, job_counter);
	std::string command;

	if (joboptions["fn_model"].getString() == "" &&
			joboptions["fn_mic"].getString() == "" && joboptions["fn_data"].getString() == "")
	{
		// Nothing was selected...
		error_message = "Please select an input file.";
		return false;
	}

	int c = 0;
	if (joboptions["do_select_values"].getBoolean()) c++;
	if (joboptions["do_discard"].getBoolean()) c++;
	if (joboptions["do_split"].getBoolean()) c++;
	if (joboptions["do_remove_duplicates"].getBoolean()) c++;
	if (joboptions["do_filaments"].getBoolean()) c++;
	if (c > 1)
	{
		error_message = "You cannot do many tasks simultaneously...";
		return false;
	}

	if (joboptions["do_filaments"].getBoolean())
	{
		label += ".filamentsdendrogram";
		command="`which relion_filament_selection`";

		if (joboptions["fn_mic"].getString() != "" || joboptions["fn_data"].getString() != "")
		{
			error_message = "ERROR: Filament selection by dendrogram analysis is only possible for optimiser STAR files...";
			return false;
		}

		if (joboptions["fn_model"].getString() == "")
		{
			error_message = "ERROR: Filament selection by dendrogram analysis needs an optimiser STAR file...";
			return false;
		}

 		Node node(joboptions["fn_model"].getString(), joboptions["fn_model"].node_type);
		inputNodes.push_back(node);

		FileName fn_out = outputname + "run_optimiser.star";
		Node node2(fn_out, LABEL_SELECT_OPT);
		outputNodes.push_back(node2);

		Node node3(outputname + "logfile.pdf", LABEL_SELECT_LOG);
		outputNodes.push_back(node3);

		command += " -i " + joboptions["fn_model"].getString();
		command += " -o " + outputname;
		command += " -t " + joboptions["dendrogram_threshold"].getString();
		command += " -c " + joboptions["dendrogram_minclass"].getString();

	}
	else if (joboptions["do_remove_duplicates"].getBoolean())
	{

		label += ".removeduplicates";

		// Remove duplicates
		command="`which relion_star_handler`";

		if (joboptions["fn_mic"].getString() != "" || joboptions["fn_model"].getString() != "")
		{
			error_message = "ERROR: Duplicate removal is only possible for particle STAR files...";
			return false;
		}

		if (joboptions["fn_data"].getString() == "")
		{
			error_message = "ERROR: Duplicate removal needs a particle STAR file...";
			return false;
		}

		Node node(joboptions["fn_data"].getString(), joboptions["fn_data"].node_type);
		inputNodes.push_back(node);
		command += " --i " + joboptions["fn_data"].getString();

		FileName fn_out = outputname+"particles.star";
		Node node2(fn_out, LABEL_SELECT_PARTS);
		outputNodes.push_back(node2);
		command += " --o " + fn_out;

		command += " --remove_duplicates " + joboptions["duplicate_threshold"].getString();
		if (joboptions["image_angpix"].getNumber(error_message) > 0)
			command += " --image_angpix " + joboptions["image_angpix"].getString();
		if (error_message != "") return false;

	}
	else if (joboptions["do_select_values"].getBoolean() || joboptions["do_discard"].getBoolean() || joboptions["do_split"].getBoolean())
	{
		// Value-based selection
		command="`which relion_star_handler`";

		if (joboptions["fn_model"].getString() != "")
		{
			error_message = "ERROR: Value-selection or subset splitting is only possible for micrograph or particle STAR files...";
			return false;
		}

		FileName fn_out;
		if (joboptions["fn_mic"].getString() != "")
		{
			Node node(joboptions["fn_mic"].getString(), joboptions["fn_mic"].node_type);
			inputNodes.push_back(node);
			command += " --i " + joboptions["fn_mic"].getString();
			fn_out = outputname+"micrographs.star";

		}
		else if (joboptions["fn_data"].getString() != "")
		{
			Node node(joboptions["fn_data"].getString(), joboptions["fn_data"].node_type);
			inputNodes.push_back(node);
			command += " --i " + joboptions["fn_data"].getString();
			fn_out = outputname+"particles.star";
		}
		command += " --o " + fn_out;

		if (joboptions["do_select_values"].getBoolean() || joboptions["do_discard"].getBoolean())
		{

			if (joboptions["fn_mic"].getString() != "")
			{
				Node node2(fn_out, LABEL_SELECT_MICS);
				outputNodes.push_back(node2);
			}
			else if (joboptions["fn_data"].getString() != "")
			{
				Node node2(fn_out, LABEL_SELECT_PARTS);
				outputNodes.push_back(node2);
			}

			if (joboptions["do_select_values"].getBoolean())
			{
				label += ".onvalue";

				command += " --select " + joboptions["select_label"].getString();
				command += " --minval " + joboptions["select_minval"].getString();
				command += " --maxval " + joboptions["select_maxval"].getString();
			}
			else if (joboptions["do_discard"].getBoolean())
			{
				label += ".discard";

				command += " --discard_on_stats ";
				command += " --discard_label " + joboptions["discard_label"].getString();
				command += " --discard_sigma " + joboptions["discard_sigma"].getString();
			}

		}
		else if (joboptions["do_split"].getBoolean())
		{

			label += ".split";

			int nr_split=0;
			command += " --split ";
			if (joboptions["do_random"].getBoolean())
			{
				command += " --random_order ";
			}

			if (joboptions["nr_split"].getNumber(error_message) <= 0 && joboptions["split_size"].getNumber(error_message) <= 0
					&& !joboptions["nr_split"].isSchedulerVariable() && !joboptions["split_size"].isSchedulerVariable())
			{
				error_message = "ERROR: When splitting the input STAR file into subsets, set nr_split and/or split_size to a positive value";
				return false;
			}

			if (joboptions["nr_split"].getNumber(error_message) > 0 && !joboptions["nr_split"].isSchedulerVariable())
			{
				if (error_message != "") return false;

				nr_split = joboptions["nr_split"].getNumber(error_message);
				command += " --nr_split " + joboptions["nr_split"].getString();
			}
			if (joboptions["split_size"].getNumber(error_message) > 0 && !joboptions["split_size"].isSchedulerVariable())
			{
				if (error_message != "") return false;

				command += " --size_split " + joboptions["split_size"].getString();
			}

			// As of relion-3.1, star_handler will write out a star file with the output nodes, which will be read by the pipeliner
		}
	}
	else
	{

		// Automated 2D class selection through the class_ranker
		if (joboptions["do_class_ranker"].getBoolean())
		{

			label += ".class2dauto";

			if (joboptions["fn_model"].getString() == "")
			{
				error_message = "ERROR: When using automatically selecting 2D classes, one needs to provide an optimiser.star file";
				return false;
			}

			if (joboptions["do_regroup"].getBoolean() || joboptions["do_recenter"].getBoolean())
			{
				error_message = "ERROR: regrouping and recentering have not been implemented in class_ranker.";
				return false;
			}

			command = "`which relion_class_ranker`";

			// input
			command += " --opt " + joboptions["fn_model"].getString();
			Node node(joboptions["fn_model"].getString(), joboptions["fn_model"].node_type);
			inputNodes.push_back(node);

			//output
			command += " --o " + outputname + " --fn_sel_parts particles.star --fn_sel_classavgs class_averages.star";

			if (joboptions["select_nr_parts"].getNumber(error_message) > 0)
			{
				command += " --select_min_nr_particles " + joboptions["select_nr_parts"].getString();
			}
			else if (joboptions["select_nr_classes"].getNumber(error_message) > 0)
			{
				command += " --select_min_nr_classes " + joboptions["select_nr_classes"].getString();
			}

			FileName fn_parts = outputname+"particles.star";
			Node node2(fn_parts, LABEL_SELECT_PARTS);
			outputNodes.push_back(node2);

			FileName fn_imgs = outputname+"class_averages.star";
			Node node3(fn_imgs, LABEL_SELECT_CLAVS);
			outputNodes.push_back(node3);

			// Also save optimiser.star, which could be used for next manual selection (but ordered for examples on the new scores)
			command += " --fn_root rank";

			// Only save the 2D class averages for 2D jobs
			FileName fn_opt = outputname+"rank_optimiser.star";
			Node node4(fn_opt, LABEL_SELECT_OPT);
			outputNodes.push_back(node4);

			// perform the actual prediction and selection
			command += " --do_granularity_features ";
			command += " --auto_select ";
			command += " --min_score " + joboptions["rank_threshold"].getString();
		}
		else
		{

			// Interactive selection
			label += ".interactive";

			command="`which relion_display`";

			// I/O
			if (joboptions["fn_model"].getString() != "")
			{

				command += " --gui --i " + joboptions["fn_model"].getString();
				Node node(joboptions["fn_model"].getString(), joboptions["fn_model"].node_type);
				inputNodes.push_back(node);

				FileName fn_parts = outputname+"particles.star";
				command += " --allow_save --fn_parts " + fn_parts;
				Node node2(fn_parts, LABEL_SELECT_PARTS);
				outputNodes.push_back(node2);

				// Only save the 2D class averages for 2D jobs
				FileName fnt = joboptions["fn_model"].getString();
				if (fnt.contains("Class2D/"))
				{
					FileName fn_imgs = outputname+"class_averages.star";
					command += " --fn_imgs " + fn_imgs;
					Node node3(fn_imgs, LABEL_SELECT_CLAVS);
					outputNodes.push_back(node3);

					if (joboptions["do_recenter"].getBoolean())
					{
						command += " --recenter ";
					}
				}
			}
			else if (joboptions["fn_mic"].getString() != "")
			{
				command += " --gui --i " + joboptions["fn_mic"].getString();
				Node node(joboptions["fn_mic"].getString(), joboptions["fn_mic"].node_type);
				inputNodes.push_back(node);

				FileName fn_mics = outputname+"micrographs.star";
				command += " --allow_save --fn_imgs " + fn_mics;
				Node node2(fn_mics, LABEL_SELECT_MICS);
				outputNodes.push_back(node2);
			}
			else if (joboptions["fn_data"].getString() != "")
			{
				command += " --gui --i " + joboptions["fn_data"].getString();
				Node node(joboptions["fn_data"].getString(), joboptions["fn_data"].node_type);
				inputNodes.push_back(node);

				FileName fn_parts = outputname+"particles.star";
				command += " --allow_save --fn_imgs " + fn_parts;
				Node node2(fn_parts, LABEL_SELECT_PARTS);
				outputNodes.push_back(node2);
			}
		}
	}

	// Re-grouping
	if (joboptions["do_regroup"].getBoolean())
	{
		if (joboptions["fn_model"].getString() == "")
		{
			error_message = "Re-grouping only works for model.star/optimiser.star files...";
			return false;
		}
		command += " --regroup " + joboptions["nr_groups"].getString();
	}

	// Other arguments
	command += " " + joboptions["other_args"].getString();

	commands.push_back(command);

	return prepareFinalCommand(outputname, commands, final_command, do_makedir, error_message);
}

