void RelionJob::initialiseAutopickJob()
{
	hidden_name = ".gui_autopick";

	joboptions["fn_input_autopick"] = JobOption("Input micrographs for autopick:", LABEL_MICS_CPIPE, 1, "", "Input micrographs (*.{star})", "Input STAR file (preferably with CTF information) with all micrographs to pick from.");
	joboptions["angpix"] = JobOption("Pixel size in micrographs (A)", -1, 0.3, 5, 0.1, "Pixel size in Angstroms. If a CTF-containing STAR file is input, then the value given here will be ignored, and the pixel size will be calculated from the values in the STAR file. A negative value can then be given here.");
	joboptions["continue_manual"] = JobOption("OR: continue manually?", false, "If set to Yes, an Autopick job can be continued as a manualpick job, so that incorrect picks can be corrected interactively.");

	joboptions["do_log"] = JobOption("OR: use Laplacian-of-Gaussian?", false, "If set to Yes, a Laplacian-of-Gaussian blob detection will be used (you can then leave the 'References' field empty. The preferred way to autopick is by setting this to no and providing references that were generated by 2D classification from this data set in RELION. The Laplacian-of-Gaussian method may be useful to kickstart a new data set. Please note that some options in the autopick tab are ignored in this method. See help messages of each option for details.");
	joboptions["log_diam_min"] = JobOption("Min. diameter for LoG filter (A)", 200, 50, 500, 10, "The smallest allowed diameter for the blob-detection algorithm. This should correspond to the smallest size of your particles in Angstroms.");
	joboptions["log_diam_max"] = JobOption("Max. diameter for LoG filter (A)", 250, 50, 500, 10, "The largest allowed diameter for the blob-detection algorithm. This should correspond to the largest size of your particles in Angstroms.");
	joboptions["log_invert"] = JobOption("Are the particles white?", false, "Set this option to No if the particles are black, and to Yes if the particles are white.");
	joboptions["log_maxres"] = JobOption("Maximum resolution to consider (A)", 20, 10, 100, 5, "The Laplacian-of-Gaussian filter will be applied to downscaled micrographs with the corresponding size. Give a negative value to skip downscaling.");
	joboptions["log_adjust_thr"] = JobOption("Adjust default threshold (stddev):", 0, -1., 1., 0.05, "Use this to pick more (negative number -> lower threshold) or less (positive number -> higher threshold) particles compared to the default setting. The threshold is moved this many standard deviations away from the average.");
	joboptions["log_upper_thr"] = JobOption("Upper threshold (stddev):", 999., 0., 10., 0.5, "Use this to discard picks with LoG thresholds that are this many standard deviations above the average, e.g. to avoid high contrast contamination like ice and ethane droplets. Good values depend on the contrast of micrographs and need to be interactively explored; for low contrast micrographs, values of ~ 1.5 may be reasonable, but the same value will be too low for high-contrast micrographs.");

	joboptions["do_topaz"] = JobOption("OR: use Topaz?", false, "If set to Yes, topaz will be used for autopicking. Run 2 separate jobs from the Topaz tab: one for training the model and for the actual picking.");
	joboptions["do_topaz_train"] = JobOption("Perform topaz training?", false, "Set this option to Yes if you want to train a topaz model.");
	joboptions["topaz_train_picks"] = JobOption("Input picked coordinates for training:", LABEL_COORDS_CPIPE, 1, "", "Input micrographs (*.{star})", "Input STAR file (preferably with CTF information) with all micrographs to pick from.");
	joboptions["do_topaz_train_parts"] = JobOption("OR train on a set of particles? ", false, "If set to Yes, the input Coordinates above will be ignored. Instead, one uses a _data.star file from a previous 2D or 3D refinement or selection to use those particle positions for training.");
	joboptions["topaz_train_parts"] = JobOption("Particles STAR file for training: ", LABEL_PARTS_CPIPE, 1, "", "Input STAR file (*.{star})", "Filename of the STAR file with the particle coordinates to be used for training, e.g. from a previous 2D or 3D classification or selection.");
	joboptions["do_topaz_pick"] = JobOption("Perform topaz picking?", false, "Set this option to Yes if you want to use a topaz model for autopicking.");
    joboptions["topaz_particle_diameter"] = JobOption("Particle diameter (A) ", -1, 0, 2000, 20, "Diameter of the particle (to be used to infer topaz downscale factor and particle radius)");
	joboptions["topaz_nr_particles"] = JobOption("Nr of particles per micrograph: ", -1, 0, 2000, 20, "Expected average number of particles per micrograph");
	joboptions["topaz_model"] = JobOption("Trained topaz model: ", "", "SAV Files (*.sav)", ".", "Trained topaz model for topaz-based picking. Use on job for training and a next job for picking. Leave this empty to use the default (general) model.");
	joboptions["fn_topaz_exe"]= JobOption("Topaz executable:", std::string("relion_python_topaz"), "Executable for running topaz. The default relion_python_topaz gets installed automatically through conda in a typical relion install. Only change this if this executable gives you problems.");
    joboptions["do_topaz_filaments"] = JobOption("Pick filaments?", false, "If set to Yes, this option will activate the -f option in our modified version of topaz that can pick filaments, as described in Lovestam & Scheres, Faraday Discussions 2022");
    joboptions["topaz_filament_threshold"] = JobOption("Threshold:", std::string("-5"),  "This sets the filament picking threshold and the length of the Hough transform, as described in Lovestam & Scheres, Faraday Discussions 2022. Useful values in our work on recombinant tau for the threshold range from −4 to −7. We typically do not change the default length of the Hough transform, which is set to be equal to the particle diameter when a negative value is given here. You can provide the additional option -fp to display images of intermediate steps of the algorithm to tune difficult cases.");
    joboptions["topaz_hough_length"] = JobOption("Hough length (A):", std::string("-1"), "This sets the filament picking threshold and the length of the Hough transform, as described in Lovestam & Scheres, Faraday Discussions 2022. Useful values in our work on recombinant tau for the threshold range from −4 to −7. We typically do not change the default length of the Hough transform, which is set to be equal to the particle diameter when a negative value is given here. You can provide the additional option -fp to display images of intermediate steps of the algorithm to tune difficult cases.");
	joboptions["topaz_other_args"]= JobOption("Additional topaz arguments:", std::string(""), "These additional arguments will be passed onto all topaz programs.");

	joboptions["do_refs"] = JobOption("Use reference-based template-matching?", false, "If set to Yes, 2D or 3D references, as defined on the References tab will be used for autopicking.");
	joboptions["fn_refs_autopick"] = JobOption("2D references:", LABEL_2DIMGS_CPIPE, 1, "", "Input references (*.{star,mrcs})", "Input STAR file or MRC stack with the 2D references to be used for picking. Note that the absolute greyscale needs to be correct, so only use images created by RELION itself, e.g. by 2D class averaging or projecting a RELION reconstruction.");
	joboptions["do_ref3d"]= JobOption("OR: provide a 3D reference?", false, "Set this option to Yes if you want to provide a 3D map, which will be projected into multiple directions to generate 2D references.");
	joboptions["fn_ref3d_autopick"] = JobOption("3D reference:", LABEL_MAP_CPIPE, 1, "", "Input reference (*.{mrc})", "Input MRC file with the 3D reference maps, from which 2D references will be made by projection. Note that the absolute greyscale needs to be correct, so only use maps created by RELION itself from this data set.");
	joboptions["ref3d_symmetry"] = JobOption("Symmetry:", std::string("C1"), "Symmetry point group of the 3D reference. Only projections in the asymmetric part of the sphere will be generated.");
	joboptions["ref3d_sampling"] = JobOption("3D angular sampling:", job_sampling_options, 0, "There are only a few discrete \
angular samplings possible because we use the HealPix library to generate the sampling of the first two Euler angles on the sphere. \
The samplings are approximate numbers and vary slightly over the sphere.\n\n For autopicking, 30 degrees is usually fine enough, but for highly symmetrical objects one may need to go finer to adequately sample the asymmetric part of the sphere.");

	joboptions["lowpass"] = JobOption("Lowpass filter references (A)", 20, 10, 100, 5, "Lowpass filter that will be applied to the references before template matching. Do NOT use very high-resolution templates to search your micrographs. The signal will be too weak at high resolution anyway, and you may find Einstein from noise.... Give a negative value to skip the lowpass filter.");
	joboptions["highpass"] = JobOption("Highpass filter (A)", -1, 100, 1000, 100, "Highpass filter that will be applied to the micrographs. This may be useful to get rid of background ramps due to uneven ice distributions. Give a negative value to skip the highpass filter.  Useful values are often in the range of 200-400 Angstroms.");
	joboptions["angpix_ref"] = JobOption("Pixel size in references (A)", -1, 0.3, 5, 0.1, "Pixel size in Angstroms for the provided reference images. This will be used to calculate the filters and the particle diameter in pixels. If a negative value is given here, the pixel size in the references will be assumed to be the same as the one in the micrographs, i.e. the particles that were used to make the references were not rescaled upon extraction.");
	joboptions["psi_sampling_autopick"] = JobOption("In-plane angular sampling (deg)", 5, 1, 30, 1, "Angular sampling in degrees for exhaustive searches of the in-plane rotations for all references.");

	joboptions["do_invert_refs"] = JobOption("References have inverted contrast?", true, "Set to Yes to indicate that the reference have inverted contrast with respect to the particles in the micrographs.");
	joboptions["do_ctf_autopick"] = JobOption("Are References CTF corrected?", true, "Set to Yes if the references were created with CTF-correction inside RELION. \n \n If set to Yes, the input micrographs can only be given as a STAR file, which should contain the CTF information for each micrograph.");
	joboptions["do_ignore_first_ctfpeak_autopick"] = JobOption("Ignore CTFs until first peak?", false,"Set this to Yes, only if this option was also used to generate the references.");

	joboptions["threshold_autopick"] = JobOption("Picking threshold:", 0.05, 0, 1., 0.01, "Use lower thresholds to pick more particles (and more junk probably).\
\n\nThis option is ignored in the Laplacian-of-Gaussian picker. Please use 'Adjust default threshold' in the 'Laplacian' tab instead.");
	joboptions["mindist_autopick"] = JobOption("Minimum inter-particle distance (A):", 100, 0, 1000, 20, "Particles closer together than this distance will be consider to be a single cluster. From each cluster, only one particle will be picked. \
\n\nThis option takes no effect for picking helical segments. The inter-box distance is calculated with the number of asymmetrical units and the helical rise on 'Helix' tab. This option is also ignored in the Laplacian-of-Gaussian picker. The inter-box distance is calculated from particle diameters.");
	joboptions["maxstddevnoise_autopick"] = JobOption("Maximum stddev noise:", 1.1, 0.9, 1.5, 0.02, "This is useful to prevent picking in carbon areas, or areas with big contamination features. Peaks in areas where the background standard deviation in the normalized micrographs is higher than this value will be ignored. Useful values are probably in the range 1.0 to 1.2. Set to -1 to switch off the feature to eliminate peaks due to high background standard deviations.\
\n\nThis option is ignored in the Laplacian-of-Gaussian picker.");
	joboptions["minavgnoise_autopick"] = JobOption("Minimum avg noise:", -999., -2, 0.5, 0.05, "This is useful to prevent picking in carbon areas, or areas with big contamination features. Peaks in areas where the background standard deviation in the normalized micrographs is higher than this value will be ignored. Useful values are probably in the range -0.5 to 0. Set to -999 to switch off the feature to eliminate peaks due to low average background densities.\
\n\nThis option is ignored in the Laplacian-of-Gaussian picker.");
	joboptions["do_write_fom_maps"] = JobOption("Write FOM maps?", false, "If set to Yes, intermediate probability maps will be written out, which (upon reading them back in) will speed up tremendously the optimization of the threshold and inter-particle distance parameters. However, with this option, one cannot run in parallel, as disc I/O is very heavy with this option set.");
	joboptions["do_read_fom_maps"] = JobOption("Read FOM maps?", false, "If written out previously, read the FOM maps back in and re-run the picking to quickly find the optimal threshold and inter-particle distance parameters");

	joboptions["shrink"] = JobOption("Shrink factor:", 0, 0, 1, 0.1, "This is useful to speed up the calculations, and to make them less memory-intensive. The micrographs will be downscaled (shrunk) to calculate the cross-correlations, and peak searching will be done in the downscaled FOM maps. When set to 0, the micrographs will de downscaled to the lowpass filter of the references, a value between 0 and 1 will downscale the micrographs by that factor. Note that the results will not be exactly the same when you shrink micrographs!\
\n\nIn the Laplacian-of-Gaussian picker, this option is ignored and the shrink factor always becomes 0.");
	joboptions["use_gpu"] = JobOption("Use GPU acceleration?", false, "If set to Yes, the job will try to use GPU acceleration. The Laplacian-of-Gaussian picker does not support GPU.");
	joboptions["gpu_ids"] = JobOption("Which GPUs to use:", std::string(""), "This argument is not necessary. If left empty, the job itself will try to allocate available GPU resources. You can override the default allocation by providing a list of which GPUs (0,1,2,3, etc) to use. MPI-processes are separated by ':'. For example: 0:1:0:1:0:1");

	joboptions["do_pick_helical_segments"] = JobOption("Pick 2D helical segments?", false, "Set to Yes if you want to pick 2D helical segments. Note this will run the old algorithms for reference-based helical segment picking, as described by He & Scheres, J Struct Biol, 2017. Often, we now run filament picking from the Topaz tab instead....");
	joboptions["do_amyloid"] = JobOption("Pick amyloid segments?", false, "Set to Yes if you want to use the algorithm that was developed specifically for picking amyloids.");

	joboptions["helical_tube_outer_diameter"] = JobOption("Tube diameter (A): ", 200, 100, 1000, 10, "Outer diameter (in Angstroms) of helical tubes. \
This value should be slightly larger than the actual width of the tubes.");
	joboptions["helical_nr_asu"] = JobOption("Number of unique asymmetrical units:", 1, 1, 100, 1, "Number of unique helical asymmetrical units in each segment box. This integer should not be less than 1. The inter-box distance (pixels) = helical rise (Angstroms) * number of asymmetrical units / pixel size (Angstroms). \
The optimal inter-box distance might also depend on the box size, the helical rise and the flexibility of the structure. In general, an inter-box distance of ~10% * the box size seems appropriate.");
	joboptions["helical_rise"] = JobOption("Helical rise (A):", -1, 0, 100, 0.01, "Helical rise in Angstroms. (Please click '?' next to the option above for details about how the inter-box distance is calculated.)");
	joboptions["helical_tube_kappa_max"] = JobOption("Maximum curvature (kappa): ", 0.1, 0.05, 0.5, 0.01, "Maximum curvature allowed for picking helical tubes. \
Kappa = 0.3 means that the curvature of the picked helical tubes should not be larger than 30% the curvature of a circle (diameter = particle mask diameter). \
Kappa ~ 0.05 is recommended for long and straight tubes (e.g. TMV, VipA/VipB and AChR tubes) while 0.20 ~ 0.40 seems suitable for flexible ones (e.g. ParM and MAVS-CARD filaments).");
	joboptions["helical_tube_length_min"] = JobOption("Minimum length (A): ", -1, 100, 1000, 10, "Minimum length (in Angstroms) of helical tubes for auto-picking. \
Helical tubes with shorter lengths will not be picked. Note that a long helical tube seen by human eye might be treated as short broken pieces due to low FOM values or high picking threshold.");
}

bool RelionJob::getCommandsAutopickJob(std::string &outputname, std::vector<std::string> &commands,
		std::string &final_command, bool do_makedir, int job_counter, std::string &error_message)
{
	commands.clear();
	initialisePipeline(outputname, job_counter);

	std::string command;
	if (is_continue && joboptions["continue_manual"].getBoolean())
	{

		label += ".continuemanual";

		command="`which relion_manualpick`";

		command += " --i " + joboptions["fn_input_autopick"].getString();
		command += " --odir " + outputname;
		command += " --pickname autopick";

		Node node(joboptions["fn_input_autopick"].getString(), joboptions["fn_input_autopick"].node_type);
		inputNodes.push_back(node);

		// Output new version: no longer save coords_suffix nodetype, but 2-column list of micrographs and coordinate files
		Node node2(outputname + "autopick.star", LABEL_AUTOPICK_COORDS);
		outputNodes.push_back(node2);

		// The output micrographs selection
		FileName fn_outstar = outputname + "micrographs_selected.star";
		Node node3(fn_outstar, LABEL_AUTOPICK_MICS);
		outputNodes.push_back(node3);
		command += " --allow_save  --selection " + fn_outstar;

		// A manualpicker jobwindow for display of micrographs....
		FileName fn_job = ".gui_manualpick";
		if (exists(fn_job+"job.star") || exists(fn_job+"run.job"))
		{
			RelionJob manualpickjob;
			bool iscont = false;
			manualpickjob.read(fn_job.c_str(), iscont, true); // true means do initialise

			command += " --scale " + manualpickjob.joboptions["micscale"].getString();
			command += " --sigma_contrast " + manualpickjob.joboptions["sigma_contrast"].getString();
			command += " --black " + manualpickjob.joboptions["black_val"].getString();
			command += " --white " + manualpickjob.joboptions["white_val"].getString();

			if (manualpickjob.joboptions["do_startend"].getBoolean())
			{
				command += " --pick_start_end ";
			}
			if (manualpickjob.joboptions["do_topaz_denoise"].getBoolean())
			{
				command += " --topaz_denoise ";
			}
			else
			{
				std::string error_message = "";
				float mylowpass = manualpickjob.joboptions["lowpass"].getNumber(error_message);
				if (mylowpass > 0.)
					command += " --lowpass " + manualpickjob.joboptions["lowpass"].getString();

				float myhighpass = manualpickjob.joboptions["highpass"].getNumber(error_message);
				if (myhighpass > 0.)
					command += " --highpass " + manualpickjob.joboptions["highpass"].getString();

				float myangpix = manualpickjob.joboptions["angpix"].getNumber(error_message);
				if (myangpix > 0.)
					command += " --angpix " + manualpickjob.joboptions["angpix"].getString();
			}

			command += " --particle_diameter " + manualpickjob.joboptions["diameter"].getString();
			if (manualpickjob.joboptions["do_fom_threshold"].getBoolean())
			{
				command += " --minimum_pick_fom " + manualpickjob.joboptions["minimum_pick_fom"].getString();
			}

			if (manualpickjob.joboptions["do_color"].getBoolean())
			{
				command += " --color_label " + manualpickjob.joboptions["color_label"].getString();
				command += " --blue " + manualpickjob.joboptions["blue_value"].getString();
				command += " --red " + manualpickjob.joboptions["red_value"].getString();
				if (manualpickjob.joboptions["fn_color"].getString().length() > 0)
					command += " --color_star " + manualpickjob.joboptions["fn_color"].getString();
			}

		}
		else
		{
			// Just use some defaults if no .gui_manualpickjob.star exists
			command += " --scale 0.25";
			command += " --sigma_contrast 3";
			command += " --lowpass 20";
			command += " --particle_diameter 100";
		}

	}
	else
	{
		// Run autopicking
		if (joboptions["nr_mpi"].getNumber(error_message) > 1)
			command="`which relion_autopick_mpi`";
		else
			command="`which relion_autopick`";
		if (error_message != "") return false;

		// Input
		int icheck = 0;
		if (joboptions["do_log"].getBoolean()) icheck++;
		if (joboptions["do_topaz"].getBoolean()) icheck++;
		if (joboptions["do_refs"].getBoolean()) icheck++;

		if ( icheck != 1)
		{
			error_message = "ERROR: On the I/O tab specify (only) one of three methods: template-matching, LoG or topaz ...";
			return false;
		}

		if (joboptions["fn_input_autopick"].getString() == "" )
		{
			error_message = "ERROR: empty field for input STAR file...";
			return false;
		}

		command += " --fn_topaz_exe " + joboptions["fn_topaz_exe"].getString();
		command += " --i " + joboptions["fn_input_autopick"].getString();
		Node node(joboptions["fn_input_autopick"].getString(), joboptions["fn_input_autopick"].node_type);
		inputNodes.push_back(node);

		if (!(joboptions["do_topaz"].getBoolean() && joboptions["do_topaz_train"].getBoolean()))
		{

			// Output new version: no longer save coords_suffix nodetype, but 2-column list of micrographs and coordinate files
			Node node3(outputname + "autopick.star", LABEL_AUTOPICK_COORDS);
			outputNodes.push_back(node3);

			// PDF with histograms of the eigenvalues
			Node node3b(outputname + "logfile.pdf", LABEL_AUTOPICK_LOG);
			outputNodes.push_back(node3b);
		}

		command += " --odir " + outputname;
		command += " --pickname autopick";

		if (joboptions["do_topaz"].getBoolean())
		{

			label += ".topaz";

			icheck = 0;
			if (joboptions["do_topaz_train"].getBoolean()) icheck++;
			if (joboptions["do_topaz_pick"].getBoolean()) icheck++;
			if ( icheck != 1)
			{
				error_message = "ERROR: On the Topaz tab specify (only) one of two methods: training or picking...";
				return false;
			}

			if (joboptions["topaz_particle_diameter"].getNumber(error_message) > 0.)
				command += " --particle_diameter " + joboptions["topaz_particle_diameter"].getString();
			if (error_message != "") return false;

			if (joboptions["do_topaz_train"].getBoolean())
			{

				label += ".train";

				if (!joboptions["use_gpu"].getBoolean())
				{
					error_message ="ERROR: For Topaz training, specify which GPUs to use on the autopicking tab; for Topaz picking GPU usage is optional";
					return false;
				}

				command += " --topaz_train";

				if (joboptions["topaz_nr_particles"].getNumber(error_message) > 0.)
					command += " --topaz_nr_particles " + joboptions["topaz_nr_particles"].getString();
				if (error_message != "") return false;

				if (joboptions["do_topaz_train_parts"].getBoolean())
				{
					command += " --topaz_train_parts " + joboptions["topaz_train_parts"].getString();
					// Output new version: no longer save coords_suffix nodetype, but 2-column list of micrographs and coordinate files
					Node nodet(outputname + "input_training_coords.star", LABEL_COORDS_CPIPE);
					outputNodes.push_back(nodet);

				}
				else
				{
					command += " --topaz_train_picks " + joboptions["topaz_train_picks"].getString();
				}

			}
			else if (joboptions["do_topaz_pick"].getBoolean())
			{
				label += ".pick";

				command += " --topaz_extract";
				if (joboptions["topaz_model"].getString() != "")
					command += " --topaz_model " + joboptions["topaz_model"].getString();

				if (joboptions["do_topaz_filaments"].getBoolean())
                {
					command += " --helix ";
                    command += " --topaz_threshold " + joboptions["topaz_filament_threshold"].getString();
                    if (joboptions["topaz_hough_length"].getNumber(error_message) > 0.)
                    {
                        command += " --helical_tube_length_min " + joboptions["topaz_hough_length"].getString();
                    }
                }

			}

			if ((joboptions["topaz_other_args"].getString()).length() > 0)
				command += " --topaz_args \" " + joboptions["topaz_other_args"].getString() + " \"";

			// GPU-stuff
			if (joboptions["use_gpu"].getBoolean())
			{
				command += " --gpu \"" + joboptions["gpu_ids"].getString() + "\"";
			}

		}
		else if (joboptions["do_log"].getBoolean())
		{
			if (joboptions["use_gpu"].getBoolean())
			{
				error_message ="ERROR: The Laplacian-of-Gaussian picker does not support GPU.";
				return false;
			}

			label += ".log";

			command += " --LoG ";
			command += " --LoG_diam_min " + joboptions["log_diam_min"].getString();
			command += " --LoG_diam_max " + joboptions["log_diam_max"].getString();
			command += " --shrink 0 --lowpass " + joboptions["log_maxres"].getString();
			command += " --LoG_adjust_threshold " + joboptions["log_adjust_thr"].getString();
			if (joboptions["log_upper_thr"].getNumber(error_message) < 999.)
				command += " --LoG_upper_threshold " + joboptions["log_upper_thr"].getString();
			if (error_message != "") return false;

			if (joboptions["log_invert"].getBoolean())
				command += " --Log_invert ";
		}
		else if (joboptions["do_refs"].getBoolean())
		{
			if (joboptions["do_ref3d"].getBoolean())
			{

				if (joboptions["fn_ref3d_autopick"].getString() == "")
				{
					error_message ="ERROR: empty field for 3D reference...";
					return false;
				}

				label += ".ref3d";

				command += " --ref " + joboptions["fn_ref3d_autopick"].getString();
				Node node2(joboptions["fn_ref3d_autopick"].getString(), LABEL_MAP_CPIPE);
				inputNodes.push_back(node2);
				command += " --sym " + joboptions["ref3d_symmetry"].getString();

				// Sampling
				int ref3d_sampling = JobOption::getHealPixOrder(joboptions["ref3d_sampling"].getString());
				if (ref3d_sampling <= 0)
				{
					error_message = "Wrong choice for ref3d_sampling";
					return false;
				}

				command += " --healpix_order " + integerToString(ref3d_sampling);
			}
			else
			{
				if (joboptions["fn_refs_autopick"].getString() == "")
				{
					error_message ="ERROR: empty field for references...";
					return false;
				}

				label += ".ref2d";

				command += " --ref " + joboptions["fn_refs_autopick"].getString();
				Node node2(joboptions["fn_refs_autopick"].getString(), LABEL_2DIMGS_CPIPE);
				inputNodes.push_back(node2);
			}

			if (joboptions["do_invert_refs"].getBoolean())
				command += " --invert ";

			if (joboptions["do_ctf_autopick"].getBoolean())
			{
				command += " --ctf ";
				if (joboptions["do_ignore_first_ctfpeak_autopick"].getBoolean())
					command += " --ctf_intact_first_peak ";
			}
			command += " --ang " + joboptions["psi_sampling_autopick"].getString();

			command += " --shrink " + joboptions["shrink"].getString();
			if (joboptions["lowpass"].getNumber(error_message) > 0.)
				command += " --lowpass " + joboptions["lowpass"].getString();
			if (error_message != "") return false;

			if (joboptions["highpass"].getNumber(error_message) > 0.)
				command += " --highpass " + joboptions["highpass"].getString();
			if (error_message != "") return false;

			if (joboptions["angpix"].getNumber(error_message) > 0.)
				command += " --angpix " + joboptions["angpix"].getString();
			if (error_message != "") return false;

			if (joboptions["angpix_ref"].getNumber(error_message) > 0.)
				command += " --angpix_ref " + joboptions["angpix_ref"].getString();
			if (error_message != "") return false;

			command += " --threshold " + joboptions["threshold_autopick"].getString();
			if (joboptions["do_pick_helical_segments"].getBoolean())
				command += " --min_distance " + floatToString(joboptions["helical_nr_asu"].getNumber(error_message) * joboptions["helical_rise"].getNumber(error_message));
			else
				command += " --min_distance " + joboptions["mindist_autopick"].getString();
			if (error_message != "") return false;

			command += " --max_stddev_noise " + joboptions["maxstddevnoise_autopick"].getString();
			if (joboptions["minavgnoise_autopick"].getNumber(error_message) > -900.)
				command += " --min_avg_noise " + joboptions["minavgnoise_autopick"].getString();
			if (error_message != "") return false;

			// Helix
			if (joboptions["do_pick_helical_segments"].getBoolean())
			{
				command += " --helix";
				if (joboptions["do_amyloid"].getBoolean())
					command += " --amyloid";
				command += " --helical_tube_outer_diameter " + joboptions["helical_tube_outer_diameter"].getString();
				command += " --helical_tube_kappa_max " + joboptions["helical_tube_kappa_max"].getString();
				command += " --helical_tube_length_min " + joboptions["helical_tube_length_min"].getString();
			}

			// GPU-stuff
			if (joboptions["use_gpu"].getBoolean())
			{
				// for the moment always use --shrink 0 with GPUs ...
				command += " --gpu \"" + joboptions["gpu_ids"].getString() + "\"";
			}

		}

		if (joboptions["do_refs"].getBoolean() || joboptions["do_log"].getBoolean())
		{

			// Although mainly for debugging, LoG-picking does have write/read_fom_maps...
			if (joboptions["do_write_fom_maps"].getBoolean())
				command += " --write_fom_maps ";

			if (joboptions["do_read_fom_maps"].getBoolean())
				command += " --read_fom_maps ";

			if (is_continue && !(joboptions["do_read_fom_maps"].getBoolean() || joboptions["do_write_fom_maps"].getBoolean()))
				command += " --only_do_unfinished ";
		}
		else if (joboptions["do_topaz"].getBoolean())
		{
			if (is_continue)
				command += " --only_do_unfinished ";
		}
	}

	// Other arguments
	command += " " + joboptions["other_args"].getString();

	commands.push_back(command);

	return prepareFinalCommand(outputname, commands, final_command, do_makedir, error_message);
}

