#
loop_
_tools.parent_id
_tools.id
_tools.category
_tools.widget
_tools.label 
_tools.help
_tools.starfile
manual     pick_lowpass radio 'Manual Picking with Low-pass filtering' ? relion_picking.star
manual     pick_denoise radio 'Manual Picking with Topaz denoising'  'If set to true, Topaz denoising will be performed instead of lowpass filtering.'
auto       'Autopicking with Laplacian-of-Gaussian' do_log radio ?
auto       'Autopicking by template matching from 2D references' ? radio ?
auto       'Autopicking by template matching from a 3D reference' ? radio ?
auto_topaz do_topaz_train radio 'Step #1: Training from input coordinates (default)'  ?
auto_topaz do_topaz_train_pctls radio 'Step #1: Training from set of particles '  ?
auto_topaz ? radio 'Step #2 - Picking'  ?
extract    ? radio 'Extract particles' ? 
extract    ? radio 'Re-extract refined particles'  ?
extract    ? radio 'Re-extract refined particles with a particle re-centering'  'If set to Yes, the input coordinates will be re-centered according to the refined origin offsets in the provided _data.star file. The unit is pixel, not angstroem. The origin is at the center of the box, not at the corner.'
class2d    ? radio '2D classification of Particles with EM algorithm'  'If set to Yes, the slower expectation-maximization algorithm will be used. This was the default option in releases prior to 4.0-beta. If set to No, then one needs to use the (faster) VDAM (variable metric gradient descent with adaptive moments) algorithm below. will be used.'
class2d    ? radio '2D classification of Particles with VDAM algorithm'  'If set to Yes, the faster VDAM (variable metric gradient descent with adaptive moments) algorithm will be used. This algorithm was introduced with relion-4.0. If set to No, then the slower EM algorithm needs to be used.'

    name: 'tools',
    icon: 'bi-wrench-adjustable',
    title: 'Tools',
    widget: 'navtab',
    default:  true, 
    children: [
      {
        name: 'manual',
        title: 'Manual Picking',
        widget: 'fieldset',
        children: [
          {
            name: 'pick_lowpass',
            title: 'Manual Picking with Low-pass filtering',
            widget: 'radio',
            option: '--do_movies',
            group: 'particles',
            help: '',
            on_click: (ev) => w_navtab_update({settings: manual_pick})
          },
          {
            name: 'pick_denoise',
            title: 'Manual Picking with Topaz denoising',
            widget: 'radio',
            option: '--do_topaz_denoise',
            group: 'particles',
            help: 'If set to true, Topaz denoising will be performed instead of lowpass filtering.',
            on_click: (ev) => w_navtab_update({settings: manual_pick_denoising})
          }

        ]
      },
      {
        name: 'auto',
        title: 'Auto Picking',
        widget: 'fieldset',
        children: [
          {
            name: 'do_log',
            title: 'Autopicking with Laplacian-of-Gaussian',
            option: '--do_log',
            widget: 'radio',
            group: 'particles',
            help: `If set to Yes, a Laplacian-of-Gaussian blob detection will be used (you can then leave the 'References' field empty. The preferred way to autopick is by setting this to no and providing references that were generated by 2D classification from this data set in RELION. The Laplacian-of-Gaussian method may be useful to kickstart a new data set. Please note that some options in the autopick tab are ignored in this method. See help messages of each option for details.`,
            on_click: (ev) => w_navtab_update({settings: autopick_log})
          },
          {
            name: 'do_refs',
            title: 'Autopicking by template matching from 2D references',
            option: '--do_micrographs',
            widget: 'radio',
            group: 'particles',
            help: 'Set this to Yes if you plan to use the UCSF implementation. The UCSF-implementation needs a GPU but uses only one CPU thread.',
            on_click: (ev) => w_navtab_update({settings: ucsf_settings})
          },
          {
            name: 'do_ref3D',
            title: 'Autopicking by template matching from a 3D reference',
            option: '--do_micrographs',
            widget: 'radio',
            group: 'particles',
            help: 'Set this option to Yes if you want to provide a 3D map, which will be projected into multiple directions to generate 2D references.',
            on_click: (ev) => w_navtab_update({settings: ucsf_settings})
          },
        ]
      },
      {
        name: 'auto_topaz',
        title: 'Auto Picking by Topaz',
        widget: 'fieldset',
        children: [

          {
            name: 'do_topaz_train',
            title: 'Step #1: Training from input coordinates (default)',
            option: '--topaz_train',
            widget: 'radio',
            group: 'particles',
            help: 'Set this option to Yes if you want to train a topaz model.',
            on_click: (ev) => w_navtab_update({settings: autopick_topaz_train})
          },
          {
            name: 'do_topaz_train_parts',
            title: 'Step #1: Training from set of particles ',
            option: '--topaz_train_parts',
            widget: 'radio',
            group: 'particles',
            help: 'Set this option to Yes if you want to train a topaz model.',
            on_click: (ev) => w_navtab_update({settings: autopick_topaz_train})
          },
          {
            name: 'do_topaz_pick',
            title: 'Step #2 - Picking',
            option: '--do_topaz_pick',
            widget: 'radio',
            group: 'particles',
            help: 'Set this to Yes if you plan to use the UCSF implementation. The UCSF-implementation needs a GPU but uses only one CPU thread.',
            on_click: (ev) => w_navtab_update({settings: autopick_topaz})
          },
        ]
      },
      {
        name: 'p_extract',
        title: 'Particle extraction',
        widget: 'fieldset',
        children: [
          {
            name:'io',
            title: 'Extract particles',
            widget: 'radio',
            on_click: (ev) => w_navtab_update({io: extract_io})
          },
          {
            name:'io',
            title: 'Re-extract refined particles',
            widget: 'radio',
            group: 'particles',
            help: 'If set to Yes, relion uses a _data.star file from a previous 2D or 3D refinement to re-extract the particles in that refinement, possibly re-centered with their refined origin offsets. This is particularly useful when going from binned to unbinned particles.',
            on_click: (ev) => w_navtab_update({io: re_extract_io})
          },
          {
            name:'io',
            title: 'Re-extract refined particles with a particle re-centering',
            widget: 'radio',
            group: 'particles',
            help: 'If set to Yes, the input coordinates will be re-centered according to the refined origin offsets in the provided _data.star file. The unit is pixel, not angstrom. The origin is at the center of the box, not at the corner.',
            on_click: (ev) => w_navtab_update({io: re_extract_io_center})
          },
        ]
      },

    ]
  },
        name: 'class2d_ptcls',
        title: 'Particles',
        widget: 'fieldset',
        children: [
          {
            name: 'do_em',
            title: '2D classification of Particles with EM algorithm',
            widget: 'radio',
            option: '--fn_model',
            group: 'toolkit',
            help: `If set to Yes, the slower expectation-maximization algorithm will be used. This was the default option in releases prior to 4.0-beta. If set to No, then one needs to use the (faster) VDAM (variable metric gradient descent with adaptive moments) algorithm below. will be used.`,
            on_click: (ev) => w_navtab_update({io: class2d_io_tab, settings: class2d_ptcls_em_tab})
          },
          {
            name: 'do_grad',
            title: '2D classification of Particles with VDAM algorithm',
            widget: 'radio',
            option: '--fn_model',
            group: 'toolkit',
            help: `If set to Yes, the faster VDAM algorithm will be used. This algorithm was introduced with relion-4.0. If set to No, then the slower EM algorithm needs to be used.`,
            on_click: (ev) => w_navtab_update({io: class2d_io_tab, settings: class2d_ptcls_vdam_tab})
          },
        ]
      },

